/**
 * 深圳小学英语课本词汇（沪教牛津版·深圳用）
 * 按年级分册整理：小一上 ~ 小六下
 * 词汇来源：沪教牛津版（深圳用）课本各单元单词表
 */

export interface PresetVocab {
  name: string
  words: Array<{ word: string; meaning: string; phonetic?: string }>
}

export const shenzhenPrimaryVocab: Record<string, PresetVocab> = {
  '小一上': {
    name: '小一上',
    words: [
      // Unit 1 Greetings
      { word: 'hello', meaning: '你好', phonetic: '/həˈloʊ/' },
      { word: 'hi', meaning: '嗨', phonetic: '/haɪ/' },
      { word: 'goodbye', meaning: '再见', phonetic: '/ɡʊdˈbaɪ/' },
      { word: 'morning', meaning: '早上', phonetic: '/ˈmɔːrnɪŋ/' },
      { word: 'afternoon', meaning: '下午', phonetic: '/ˌæftərˈnuːn/' },
      { word: 'evening', meaning: '晚上', phonetic: '/ˈiːvnɪŋ/' },
      { word: 'night', meaning: '夜晚', phonetic: '/naɪt/' },
      { word: 'nice', meaning: '好的', phonetic: '/naɪs/' },
      { word: 'see', meaning: '看见', phonetic: '/siː/' },
      { word: 'you', meaning: '你', phonetic: '/juː/' },
      // Unit 2 School things
      { word: 'give', meaning: '给', phonetic: '/ɡɪv/' },
      { word: 'me', meaning: '我', phonetic: '/miː/' },
      { word: 'a', meaning: '一个', phonetic: '/ə/' },
      { word: 'please', meaning: '请', phonetic: '/pliːz/' },
      { word: 'thank', meaning: '谢谢', phonetic: '/θæŋk/' },
      { word: 'ruler', meaning: '尺子', phonetic: '/ˈruːlər/' },
      { word: 'book', meaning: '书', phonetic: '/bʊk/' },
      { word: 'pencil', meaning: '铅笔', phonetic: '/ˈpensl/' },
      { word: 'rubber', meaning: '橡皮', phonetic: '/ˈrʌbər/' },
      { word: 'how', meaning: '多么', phonetic: '/haʊ/' },
      { word: 'for', meaning: '为；给', phonetic: '/fɔːr/' },
      // Unit 3 My face
      { word: 'this', meaning: '这；这个', phonetic: '/ðɪs/' },
      { word: 'is', meaning: '是', phonetic: '/ɪz/' },
      { word: 'my', meaning: '我的', phonetic: '/maɪ/' },
      { word: 'your', meaning: '你的', phonetic: '/jɔːr/' },
      { word: 'eye', meaning: '眼睛', phonetic: '/aɪ/' },
      { word: 'ear', meaning: '耳朵', phonetic: '/ɪr/' },
      { word: 'nose', meaning: '鼻子', phonetic: '/noʊz/' },
      { word: 'mouth', meaning: '嘴巴', phonetic: '/maʊθ/' },
      { word: 'face', meaning: '脸', phonetic: '/feɪs/' },
      // Unit 4 Abilities
      { word: 'I', meaning: '我', phonetic: '/aɪ/' },
      { word: 'what', meaning: '什么', phonetic: '/wɑːt/' },
      { word: 'flower', meaning: '花', phonetic: '/ˈflaʊər/' },
      { word: 'house', meaning: '房子', phonetic: '/haʊs/' },
      { word: 'sing', meaning: '唱歌', phonetic: '/sɪŋ/' },
      { word: 'dance', meaning: '跳舞', phonetic: '/dæns/' },
      { word: 'read', meaning: '读', phonetic: '/riːd/' },
      { word: 'draw', meaning: '画画', phonetic: '/drɔː/' },
      // Unit 5 My family
      { word: 'who', meaning: '谁', phonetic: '/huː/' },
      { word: 'she', meaning: '她', phonetic: '/ʃiː/' },
      { word: 'he', meaning: '他', phonetic: '/hiː/' },
      { word: 'grandfather', meaning: '爷爷', phonetic: '/ˈɡrænfɑːðər/' },
      { word: 'grandmother', meaning: '奶奶', phonetic: '/ˈɡrænmʌðər/' },
      { word: 'father', meaning: '父亲', phonetic: '/ˈfɑːðər/' },
      { word: 'mother', meaning: '母亲', phonetic: '/ˈmʌðər/' },
      { word: 'yes', meaning: '是的', phonetic: '/jes/' },
      { word: 'no', meaning: '不', phonetic: '/noʊ/' },
      { word: 'mummy', meaning: '妈妈', phonetic: '/ˈmʌmi/' },
      { word: 'daddy', meaning: '爸爸', phonetic: '/ˈdædi/' },
      { word: 'sister', meaning: '姐妹', phonetic: '/ˈsɪstər/' },
      { word: 'brother', meaning: '兄弟', phonetic: '/ˈbrʌðər/' },
      { word: 'baby', meaning: '宝贝', phonetic: '/ˈbeɪbi/' },
      { word: 'finger', meaning: '手指', phonetic: '/ˈfɪŋɡər/' },
      // Unit 6 My friends
      { word: 'look', meaning: '看', phonetic: '/lʊk/' },
      { word: 'tall', meaning: '高的', phonetic: '/tɔːl/' },
      { word: 'thin', meaning: '瘦的', phonetic: '/θɪn/' },
      { word: 'fat', meaning: '胖的', phonetic: '/fæt/' },
      { word: 'short', meaning: '矮的；短的', phonetic: '/ʃɔːrt/' },
      { word: 'classmate', meaning: '同学', phonetic: '/ˈklæsmeɪt/' },
      { word: 'friend', meaning: '朋友', phonetic: '/frend/' },
      // Unit 7 Numbers
      { word: 'how many', meaning: '多少', phonetic: '/haʊ ˈmeni/' },
      { word: 'one', meaning: '一', phonetic: '/wʌn/' },
      { word: 'two', meaning: '二', phonetic: '/tuː/' },
      { word: 'three', meaning: '三', phonetic: '/θriː/' },
      { word: 'four', meaning: '四', phonetic: '/fɔːr/' },
      { word: 'five', meaning: '五', phonetic: '/faɪv/' },
      { word: 'six', meaning: '六', phonetic: '/sɪks/' },
      { word: 'seven', meaning: '七', phonetic: '/ˈsevn/' },
      { word: 'eight', meaning: '八', phonetic: '/eɪt/' },
      { word: 'nine', meaning: '九', phonetic: '/naɪn/' },
      { word: 'ten', meaning: '十', phonetic: '/ten/' },
      { word: 'paper', meaning: '纸', phonetic: '/ˈpeɪpər/' },
      { word: 'rabbit', meaning: '兔子', phonetic: '/ˈræbɪt/' },
      // Unit 8 Fruits
      { word: 'apple', meaning: '苹果', phonetic: '/ˈæpl/' },
      { word: 'pear', meaning: '梨', phonetic: '/per/' },
      { word: 'peach', meaning: '桃子', phonetic: '/piːtʃ/' },
      { word: 'orange', meaning: '橘子', phonetic: '/ˈɒrɪndʒ/' },
      { word: 'like', meaning: '喜欢', phonetic: '/laɪk/' },
    ],
  },
  '小一下': {
    name: '小一下',
    words: [
      // Unit 1 Toys
      { word: 'ball', meaning: '球', phonetic: '/bɔːl/' },
      { word: 'doll', meaning: '玩具娃娃', phonetic: '/dɒl/' },
      { word: 'kite', meaning: '风筝', phonetic: '/kaɪt/' },
      { word: 'bicycle', meaning: '自行车', phonetic: '/ˈbaɪsɪkl/' },
      { word: 'toy', meaning: '玩具', phonetic: '/tɔɪ/' },
      { word: 'slide', meaning: '滑梯', phonetic: '/slaɪd/' },
      { word: 'swing', meaning: '秋千', phonetic: '/swɪŋ/' },
      { word: 'balloon', meaning: '气球', phonetic: '/bəˈluːn/' },
      { word: 'can', meaning: '能', phonetic: '/kæn/' },
      { word: 'play', meaning: '玩', phonetic: '/pleɪ/' },
      // Unit 2 Food
      { word: 'rice', meaning: '米饭', phonetic: '/raɪs/' },
      { word: 'soup', meaning: '汤', phonetic: '/suːp/' },
      { word: 'meat', meaning: '肉', phonetic: '/miːt/' },
      { word: 'noodles', meaning: '面条', phonetic: '/ˈnuːdlz/' },
      { word: 'cake', meaning: '蛋糕', phonetic: '/keɪk/' },
      { word: 'egg', meaning: '鸡蛋', phonetic: '/eɡ/' },
      { word: 'milk', meaning: '牛奶', phonetic: '/mɪlk/' },
      { word: 'water', meaning: '水', phonetic: '/ˈwɔːtər/' },
      { word: 'bread', meaning: '面包', phonetic: '/bred/' },
      { word: 'biscuit', meaning: '饼干', phonetic: '/ˈbɪskɪt/' },
      { word: 'pizza', meaning: '比萨饼', phonetic: '/ˈpiːtsə/' },
      { word: 'hotdog', meaning: '热狗', phonetic: '/ˈhɑːtdɔːɡ/' },
      { word: 'juice', meaning: '果汁', phonetic: '/dʒuːs/' },
      { word: 'cola', meaning: '可乐', phonetic: '/ˈkoʊlə/' },
      // Unit 3 Drinks and fruits
      { word: 'lemon', meaning: '柠檬', phonetic: '/ˈlemən/' },
      { word: 'melon', meaning: '瓜', phonetic: '/ˈmelən/' },
      { word: 'banana', meaning: '香蕉', phonetic: '/bəˈnænə/' },
      { word: 'sweet', meaning: '甜的', phonetic: '/swiːt/' },
      { word: 'sour', meaning: '酸的', phonetic: '/saʊr/' },
      // Unit 4 Seasons
      { word: 'spring', meaning: '春天', phonetic: '/sprɪŋ/' },
      { word: 'summer', meaning: '夏天', phonetic: '/ˈsʌmər/' },
      { word: 'autumn', meaning: '秋天', phonetic: '/ˈɔːtəm/' },
      { word: 'winter', meaning: '冬天', phonetic: '/ˈwɪntər/' },
      { word: 'cold', meaning: '冷的', phonetic: '/koʊld/' },
      { word: 'cool', meaning: '凉爽的', phonetic: '/kuːl/' },
      { word: 'warm', meaning: '温暖的', phonetic: '/wɔːrm/' },
      { word: 'hot', meaning: '热的', phonetic: '/hɑːt/' },
      { word: 'sun', meaning: '太阳', phonetic: '/sʌn/' },
      { word: 'cloud', meaning: '云', phonetic: '/klaʊd/' },
      { word: 'wind', meaning: '风', phonetic: '/wɪnd/' },
      { word: 'rain', meaning: '雨', phonetic: '/reɪn/' },
      { word: 'snow', meaning: '雪', phonetic: '/snoʊ/' },
      { word: 'leaf', meaning: '树叶', phonetic: '/liːf/' },
      { word: 'moon', meaning: '月亮', phonetic: '/muːn/' },
      { word: 'mooncake', meaning: '月饼', phonetic: '/ˈmuːnkeɪk/' },
      // Unit 5 Colours
      { word: 'red', meaning: '红色的', phonetic: '/red/' },
      { word: 'blue', meaning: '蓝色的', phonetic: '/bluː/' },
      { word: 'green', meaning: '绿色的', phonetic: '/ɡriːn/' },
      { word: 'yellow', meaning: '黄色的', phonetic: '/ˈjeloʊ/' },
      { word: 'black', meaning: '黑色的', phonetic: '/blæk/' },
      { word: 'white', meaning: '白色的', phonetic: '/waɪt/' },
      { word: 'brown', meaning: '棕色的', phonetic: '/braʊn/' },
      { word: 'pink', meaning: '粉色的', phonetic: '/pɪŋk/' },
      { word: 'purple', meaning: '紫色的', phonetic: '/ˈpɜːrpl/' },
      { word: 'orange', meaning: '橙色的', phonetic: '/ˈɒrɪndʒ/' },
      // Unit 6 Jobs
      { word: 'postman', meaning: '邮递员', phonetic: '/ˈpoʊstmən/' },
      { word: 'policeman', meaning: '警察', phonetic: '/pəˈliːsmən/' },
      { word: 'fireman', meaning: '消防员', phonetic: '/ˈfaɪərmən/' },
      { word: 'milkman', meaning: '送奶员', phonetic: '/ˈmɪlkmən/' },
      { word: 'fisherman', meaning: '渔民', phonetic: '/ˈfɪʃərmən/' },
      { word: 'farmer', meaning: '农民', phonetic: '/ˈfɑːrmər/' },
      { word: 'teacher', meaning: '老师', phonetic: '/ˈtiːtʃər/' },
      { word: 'driver', meaning: '司机', phonetic: '/ˈdraɪvər/' },
      { word: 'doctor', meaning: '医生', phonetic: '/ˈdɑːktər/' },
      { word: 'nurse', meaning: '护士', phonetic: '/nɜːrs/' },
      { word: 'cook', meaning: '厨师', phonetic: '/kʊk/' },
      // Unit 7 Clothes
      { word: 'hat', meaning: '帽子', phonetic: '/hæt/' },
      { word: 'glove', meaning: '手套', phonetic: '/ɡlʌv/' },
      { word: 'scarf', meaning: '围巾', phonetic: '/skɑːrf/' },
      { word: 'tie', meaning: '领带', phonetic: '/taɪ/' },
      { word: 'belt', meaning: '腰带', phonetic: '/belt/' },
      { word: 'sock', meaning: '袜子', phonetic: '/sɑːk/' },
      { word: 'shirt', meaning: '衬衫', phonetic: '/ʃɜːrt/' },
      { word: 'dress', meaning: '连衣裙', phonetic: '/dres/' },
      { word: 'coat', meaning: '外套', phonetic: '/koʊt/' },
      { word: 'shoe', meaning: '鞋子', phonetic: '/ʃuː/' },
      // Adjectives
      { word: 'big', meaning: '大的', phonetic: '/bɪɡ/' },
      { word: 'small', meaning: '小的', phonetic: '/smɔːl/' },
      { word: 'new', meaning: '新的', phonetic: '/njuː/' },
      { word: 'old', meaning: '旧的', phonetic: '/oʊld/' },
      { word: 'long', meaning: '长的', phonetic: '/lɔːŋ/' },
      { word: 'young', meaning: '年轻的', phonetic: '/jʌŋ/' },
    ],
  },
  '小二上': {
    name: '小二上',
    words: [
      // Unit 1 Places
      { word: 'park', meaning: '公园', phonetic: '/pɑːrk/' },
      { word: 'road', meaning: '马路', phonetic: '/roʊd/' },
      { word: 'building', meaning: '建筑', phonetic: '/ˈbɪldɪŋ/' },
      { word: 'shop', meaning: '商店', phonetic: '/ʃɑːp/' },
      { word: 'zoo', meaning: '动物园', phonetic: '/zuː/' },
      // Unit 2 Actions
      { word: 'come', meaning: '来', phonetic: '/kʌm/' },
      { word: 'go', meaning: '去', phonetic: '/ɡoʊ/' },
      { word: 'run', meaning: '跑', phonetic: '/rʌn/' },
      { word: 'walk', meaning: '走', phonetic: '/wɔːk/' },
      { word: 'jump', meaning: '跳', phonetic: '/dʒʌmp/' },
      { word: 'swim', meaning: '游泳', phonetic: '/swɪm/' },
      { word: 'fly', meaning: '飞', phonetic: '/flaɪ/' },
      { word: 'skip', meaning: '跳绳', phonetic: '/skɪp/' },
      { word: 'climb', meaning: '攀爬', phonetic: '/klaɪm/' },
      { word: 'ride', meaning: '骑', phonetic: '/raɪd/' },
      // Unit 3 Washing
      { word: 'wash', meaning: '洗', phonetic: '/wɑːʃ/' },
      { word: 'dirty', meaning: '脏的', phonetic: '/ˈdɜːrti/' },
      { word: 'clean', meaning: '干净的', phonetic: '/kliːn/' },
      { word: 'towel', meaning: '毛巾', phonetic: '/ˈtaʊəl/' },
      { word: 'soap', meaning: '肥皂', phonetic: '/soʊp/' },
      { word: 'water', meaning: '水', phonetic: '/ˈwɔːtər/' },
      { word: 'glass', meaning: '玻璃杯', phonetic: '/ɡlæs/' },
      { word: 'toothbrush', meaning: '牙刷', phonetic: '/ˈtuːθbrʌʃ/' },
      { word: 'toothpaste', meaning: '牙膏', phonetic: '/ˈtuːθpeɪst/' },
      // Unit 4 Tableware
      { word: 'chopsticks', meaning: '筷子', phonetic: '/ˈtʃɑːpstɪks/' },
      { word: 'bowl', meaning: '碗', phonetic: '/boʊl/' },
      { word: 'plate', meaning: '盘子', phonetic: '/pleɪt/' },
      { word: 'spoon', meaning: '勺子', phonetic: '/spuːn/' },
      { word: 'fork', meaning: '叉子', phonetic: '/fɔːrk/' },
      { word: 'knife', meaning: '刀', phonetic: '/naɪf/' },
      // Unit 5 Summer
      { word: 'beach', meaning: '海滩', phonetic: '/biːtʃ/' },
      { word: 'shell', meaning: '贝壳', phonetic: '/ʃel/' },
      { word: 'sand', meaning: '沙子', phonetic: '/sænd/' },
      { word: 'star', meaning: '星星', phonetic: '/stɑːr/' },
      { word: 'sea', meaning: '大海', phonetic: '/siː/' },
      // Unit 6 Time
      { word: 'watch', meaning: '手表', phonetic: '/wɑːtʃ/' },
      { word: 'clock', meaning: '钟', phonetic: '/klɑːk/' },
      { word: 'day', meaning: '白天', phonetic: '/deɪ/' },
      { word: 'night', meaning: '夜晚', phonetic: '/naɪt/' },
      { word: 'breakfast', meaning: '早餐', phonetic: '/ˈbrekfəst/' },
      { word: 'lunch', meaning: '午餐', phonetic: '/lʌntʃ/' },
      { word: 'dinner', meaning: '晚餐', phonetic: '/ˈdɪnər/' },
      // Unit 7 Animals
      { word: 'hen', meaning: '母鸡', phonetic: '/hen/' },
      { word: 'chick', meaning: '小鸡', phonetic: '/tʃɪk/' },
      { word: 'duck', meaning: '鸭子', phonetic: '/dʌk/' },
      { word: 'cow', meaning: '奶牛', phonetic: '/kaʊ/' },
      { word: 'sheep', meaning: '绵羊', phonetic: '/ʃiːp/' },
      { word: 'pig', meaning: '猪', phonetic: '/pɪɡ/' },
      { word: 'horse', meaning: '马', phonetic: '/hɔːrs/' },
      // Unit 8 Room
      { word: 'window', meaning: '窗户', phonetic: '/ˈwɪndoʊ/' },
      { word: 'door', meaning: '门', phonetic: '/dɔːr/' },
      { word: 'bed', meaning: '床', phonetic: '/bed/' },
      { word: 'room', meaning: '房间', phonetic: '/ruːm/' },
      { word: 'sofa', meaning: '沙发', phonetic: '/ˈsoʊfə/' },
      { word: 'table', meaning: '桌子', phonetic: '/ˈteɪbl/' },
      { word: 'lamp', meaning: '台灯', phonetic: '/læmp/' },
      { word: 'home', meaning: '家', phonetic: '/hoʊm/' },
      // Adjectives
      { word: 'good', meaning: '好的', phonetic: '/ɡʊd/' },
      { word: 'bad', meaning: '坏的', phonetic: '/bæd/' },
      { word: 'right', meaning: '对的', phonetic: '/raɪt/' },
      { word: 'wrong', meaning: '错的', phonetic: '/rɔːŋ/' },
      { word: 'fast', meaning: '快的', phonetic: '/fæst/' },
      { word: 'slow', meaning: '慢的', phonetic: '/sloʊ/' },
      { word: 'easy', meaning: '容易的', phonetic: '/ˈiːzi/' },
      { word: 'hard', meaning: '困难的', phonetic: '/hɑːrd/' },
      { word: 'happy', meaning: '开心的', phonetic: '/ˈhæpi/' },
      { word: 'sad', meaning: '伤心的', phonetic: '/sæd/' },
    ],
  },
  '小二下': {
    name: '小二下',
    words: [
      // Unit 1 Family extended
      { word: 'granddaughter', meaning: '孙女', phonetic: '/ˈɡrændɔːtər/' },
      { word: 'grandson', meaning: '孙子', phonetic: '/ˈɡrænsʌn/' },
      // Unit 2 Animals
      { word: 'bear', meaning: '熊', phonetic: '/ber/' },
      { word: 'elephant', meaning: '大象', phonetic: '/ˈelɪfənt/' },
      { word: 'tiger', meaning: '老虎', phonetic: '/ˈtaɪɡər/' },
      { word: 'monkey', meaning: '猴子', phonetic: '/ˈmʌŋki/' },
      { word: 'panda', meaning: '熊猫', phonetic: '/ˈpændə/' },
      { word: 'lion', meaning: '狮子', phonetic: '/ˈlaɪən/' },
      { word: 'cat', meaning: '猫', phonetic: '/kæt/' },
      { word: 'dog', meaning: '狗', phonetic: '/dɒɡ/' },
      { word: 'fish', meaning: '鱼', phonetic: '/fɪʃ/' },
      { word: 'bird', meaning: '鸟', phonetic: '/bɜːrd/' },
      { word: 'rabbit', meaning: '兔子', phonetic: '/ˈræbɪt/' },
      { word: 'mouse', meaning: '老鼠', phonetic: '/maʊs/' },
      { word: 'tail', meaning: '尾巴', phonetic: '/teɪl/' },
      // Unit 3 Transport
      { word: 'car', meaning: '汽车', phonetic: '/kɑːr/' },
      { word: 'bus', meaning: '公共汽车', phonetic: '/bʌs/' },
      { word: 'train', meaning: '火车', phonetic: '/treɪn/' },
      { word: 'plane', meaning: '飞机', phonetic: '/pleɪn/' },
      { word: 'bike', meaning: '自行车', phonetic: '/baɪk/' },
      { word: 'boat', meaning: '船', phonetic: '/boʊt/' },
      { word: 'ship', meaning: '轮船', phonetic: '/ʃɪp/' },
      { word: 'taxi', meaning: '出租车', phonetic: '/ˈtæksi/' },
      // Unit 4 Subjects
      { word: 'Chinese', meaning: '语文；中文', phonetic: '/tʃaɪˈniːz/' },
      { word: 'English', meaning: '英语', phonetic: '/ˈɪŋɡlɪʃ/' },
      { word: 'math', meaning: '数学', phonetic: '/mæθ/' },
      { word: 'music', meaning: '音乐', phonetic: '/ˈmjuːzɪk/' },
      { word: 'art', meaning: '美术', phonetic: '/ɑːrt/' },
      { word: 'PE', meaning: '体育', phonetic: '/piː iː/' },
      // Unit 5 Body
      { word: 'head', meaning: '头', phonetic: '/hed/' },
      { word: 'hand', meaning: '手', phonetic: '/hænd/' },
      { word: 'foot', meaning: '脚', phonetic: '/fʊt/' },
      { word: 'leg', meaning: '腿', phonetic: '/leɡ/' },
      { word: 'arm', meaning: '手臂', phonetic: '/ɑːrm/' },
      { word: 'hair', meaning: '头发', phonetic: '/her/' },
      // Unit 6 Garden
      { word: 'tree', meaning: '树', phonetic: '/triː/' },
      { word: 'flower', meaning: '花', phonetic: '/ˈflaʊər/' },
      { word: 'grass', meaning: '草', phonetic: '/ɡræs/' },
      { word: 'garden', meaning: '花园', phonetic: '/ˈɡɑːrdn/' },
      // Unit 7 More actions
      { word: 'sit', meaning: '坐', phonetic: '/sɪt/' },
      { word: 'stand', meaning: '站', phonetic: '/stænd/' },
      { word: 'open', meaning: '打开', phonetic: '/ˈoʊpən/' },
      { word: 'close', meaning: '关闭', phonetic: '/kloʊz/' },
      { word: 'eat', meaning: '吃', phonetic: '/iːt/' },
      { word: 'drink', meaning: '喝', phonetic: '/drɪŋk/' },
      { word: 'sleep', meaning: '睡觉', phonetic: '/sliːp/' },
      { word: 'write', meaning: '写', phonetic: '/raɪt/' },
      // Unit 8 School
      { word: 'school', meaning: '学校', phonetic: '/skuːl/' },
      { word: 'classroom', meaning: '教室', phonetic: '/ˈklæsruːm/' },
      { word: 'desk', meaning: '课桌', phonetic: '/desk/' },
      { word: 'chair', meaning: '椅子', phonetic: '/tʃer/' },
      { word: 'pen', meaning: '钢笔', phonetic: '/pen/' },
      { word: 'schoolbag', meaning: '书包', phonetic: '/ˈskuːlbæɡ/' },
      // Unit 9 More food
      { word: 'chicken', meaning: '鸡肉', phonetic: '/ˈtʃɪkɪn/' },
      { word: 'beef', meaning: '牛肉', phonetic: '/biːf/' },
      { word: 'vegetable', meaning: '蔬菜', phonetic: '/ˈvedʒtəbl/' },
      { word: 'fruit', meaning: '水果', phonetic: '/fruːt/' },
      { word: 'candy', meaning: '糖果', phonetic: '/ˈkændi/' },
      // Verbs
      { word: 'have', meaning: '有', phonetic: '/hæv/' },
      { word: 'want', meaning: '想要', phonetic: '/wɑːnt/' },
      { word: 'need', meaning: '需要', phonetic: '/niːd/' },
      { word: 'help', meaning: '帮助', phonetic: '/help/' },
      { word: 'love', meaning: '爱', phonetic: '/lʌv/' },
      { word: 'make', meaning: '制作', phonetic: '/meɪk/' },
      { word: 'take', meaning: '拿', phonetic: '/teɪk/' },
      { word: 'put', meaning: '放', phonetic: '/pʊt/' },
      { word: 'bring', meaning: '带来', phonetic: '/brɪŋ/' },
      { word: 'give', meaning: '给', phonetic: '/ɡɪv/' },
      { word: 'show', meaning: '展示', phonetic: '/ʃoʊ/' },
      { word: 'tell', meaning: '告诉', phonetic: '/tel/' },
      { word: 'find', meaning: '找到', phonetic: '/faɪnd/' },
      { word: 'try', meaning: '尝试', phonetic: '/traɪ/' },
      { word: 'use', meaning: '使用', phonetic: '/juːz/' },
    ],
  },
  '小三上': {
    name: '小三上',
    words: [
      // Unit 1 Hello
      { word: 'Miss', meaning: '小姐', phonetic: '/mɪs/' },
      { word: 'Mr', meaning: '先生', phonetic: '/ˈmɪstər/' },
      { word: 'Mrs', meaning: '太太', phonetic: '/ˈmɪsɪz/' },
      // Unit 2 How are you
      { word: 'are', meaning: '是', phonetic: '/ɑːr/' },
      { word: 'fine', meaning: '好的', phonetic: '/faɪn/' },
      { word: 'thank', meaning: '谢谢', phonetic: '/θæŋk/' },
      // Unit 3 Are you Kitty
      { word: 'am', meaning: '是', phonetic: '/æm/' },
      { word: 'girl', meaning: '女孩', phonetic: '/ɡɜːrl/' },
      { word: 'not', meaning: '不是', phonetic: '/nɑːt/' },
      { word: 'boy', meaning: '男孩', phonetic: '/bɔɪ/' },
      // Unit 4 My friends
      { word: 'friend', meaning: '朋友', phonetic: '/frend/' },
      { word: 'he', meaning: '他', phonetic: '/hiː/' },
      { word: 'short', meaning: '矮的', phonetic: '/ʃɔːrt/' },
      { word: 'tall', meaning: '高的', phonetic: '/tɔːl/' },
      { word: 'thin', meaning: '瘦的', phonetic: '/θɪn/' },
      { word: 'fat', meaning: '胖的', phonetic: '/fæt/' },
      { word: 'this', meaning: '这', phonetic: '/ðɪs/' },
      // Unit 5 My family
      { word: 'beautiful', meaning: '漂亮的', phonetic: '/ˈbjuːtɪfl/' },
      { word: 'brother', meaning: '兄弟', phonetic: '/ˈbrʌðər/' },
      { word: 'father', meaning: '父亲', phonetic: '/ˈfɑːðər/' },
      { word: 'me', meaning: '我', phonetic: '/miː/' },
      { word: 'mother', meaning: '母亲', phonetic: '/ˈmʌðər/' },
      { word: 'sister', meaning: '姐妹', phonetic: '/ˈsɪstər/' },
      { word: 'who', meaning: '谁', phonetic: '/huː/' },
      // Unit 6 Me
      { word: 'big', meaning: '大的', phonetic: '/bɪɡ/' },
      { word: 'ear', meaning: '耳朵', phonetic: '/ɪr/' },
      { word: 'eye', meaning: '眼睛', phonetic: '/aɪ/' },
      { word: 'face', meaning: '脸', phonetic: '/feɪs/' },
      { word: 'hair', meaning: '头发', phonetic: '/her/' },
      { word: 'long', meaning: '长的', phonetic: '/lɔːŋ/' },
      { word: 'look', meaning: '看', phonetic: '/lʊk/' },
      { word: 'mouth', meaning: '嘴巴', phonetic: '/maʊθ/' },
      { word: 'small', meaning: '小的', phonetic: '/smɔːl/' },
      { word: 'nose', meaning: '鼻子', phonetic: '/noʊz/' },
      // Unit 7 In the classroom
      { word: 'blackboard', meaning: '黑板', phonetic: '/ˈblækbɔːrd/' },
      { word: 'clean', meaning: '打扫', phonetic: '/kliːn/' },
      { word: 'close', meaning: '关上', phonetic: '/kloʊz/' },
      { word: 'door', meaning: '门', phonetic: '/dɔːr/' },
      { word: 'late', meaning: '迟到', phonetic: '/leɪt/' },
      { word: 'open', meaning: '打开', phonetic: '/ˈoʊpən/' },
      { word: 'please', meaning: '请', phonetic: '/pliːz/' },
      { word: 'the', meaning: '这；那', phonetic: '/ðə/' },
      { word: 'window', meaning: '窗户', phonetic: '/ˈwɪndoʊ/' },
      // Unit 8 At the fruit shop
      { word: 'a', meaning: '一个', phonetic: '/ə/' },
      { word: 'an', meaning: '一个', phonetic: '/ən/' },
      { word: 'apple', meaning: '苹果', phonetic: '/ˈæpl/' },
      { word: 'banana', meaning: '香蕉', phonetic: '/bəˈnænə/' },
      { word: 'dad', meaning: '爸爸', phonetic: '/dæd/' },
      { word: 'good', meaning: '好的', phonetic: '/ɡʊd/' },
      { word: 'here', meaning: '这里', phonetic: '/hɪr/' },
      { word: 'how much', meaning: '多少钱', phonetic: '/haʊ mʌtʃ/' },
      { word: 'it', meaning: '它', phonetic: '/ɪt/' },
      { word: 'orange', meaning: '橘子', phonetic: '/ˈɒrɪndʒ/' },
      { word: 'they', meaning: '它们', phonetic: '/ðeɪ/' },
      { word: 'what', meaning: '什么', phonetic: '/wɑːt/' },
      // Unit 9 In my room
      { word: 'bed', meaning: '床', phonetic: '/bed/' },
      { word: 'book', meaning: '书', phonetic: '/bʊk/' },
      { word: 'chair', meaning: '椅子', phonetic: '/tʃer/' },
      { word: 'desk', meaning: '书桌', phonetic: '/desk/' },
      { word: 'mum', meaning: '妈妈', phonetic: '/mʌm/' },
      { word: 'pen', meaning: '钢笔', phonetic: '/pen/' },
      { word: 'pencil', meaning: '铅笔', phonetic: '/ˈpensl/' },
      { word: 'ruler', meaning: '尺子', phonetic: '/ˈruːlər/' },
      { word: 'schoolbag', meaning: '书包', phonetic: '/ˈskuːlbæɡ/' },
      { word: 'these', meaning: '这些', phonetic: '/ðiːz/' },
      { word: 'your', meaning: '你的', phonetic: '/jɔːr/' },
      // Unit 10 Numbers
      { word: 'eight', meaning: '八', phonetic: '/eɪt/' },
      { word: 'five', meaning: '五', phonetic: '/faɪv/' },
      { word: 'four', meaning: '四', phonetic: '/fɔːr/' },
      { word: 'how many', meaning: '多少', phonetic: '/haʊ ˈmeni/' },
      { word: 'nine', meaning: '九', phonetic: '/naɪn/' },
      { word: 'one', meaning: '一', phonetic: '/wʌn/' },
      { word: 'seven', meaning: '七', phonetic: '/ˈsevn/' },
      { word: 'six', meaning: '六', phonetic: '/sɪks/' },
      { word: 'ten', meaning: '十', phonetic: '/ten/' },
      { word: 'three', meaning: '三', phonetic: '/θriː/' },
      { word: 'two', meaning: '二', phonetic: '/tuː/' },
      // Unit 11 Small animals
      { word: 'cat', meaning: '猫', phonetic: '/kæt/' },
      { word: 'dog', meaning: '狗', phonetic: '/dɒɡ/' },
      { word: 'fish', meaning: '鱼', phonetic: '/fɪʃ/' },
      { word: 'its', meaning: '它的', phonetic: '/ɪts/' },
      { word: 'mouse', meaning: '老鼠', phonetic: '/maʊs/' },
      { word: 'rabbit', meaning: '兔子', phonetic: '/ˈræbɪt/' },
      { word: 'tail', meaning: '尾巴', phonetic: '/teɪl/' },
      // Unit 12 The four seasons
      { word: 'autumn', meaning: '秋天', phonetic: '/ˈɔːtəm/' },
      { word: 'cold', meaning: '寒冷的', phonetic: '/koʊld/' },
      { word: 'cool', meaning: '凉爽的', phonetic: '/kuːl/' },
      { word: 'hot', meaning: '炎热的', phonetic: '/hɑːt/' },
      { word: 'in', meaning: '在…内', phonetic: '/ɪn/' },
      { word: 'spring', meaning: '春天', phonetic: '/sprɪŋ/' },
      { word: 'summer', meaning: '夏天', phonetic: '/ˈsʌmər/' },
      { word: 'warm', meaning: '温暖的', phonetic: '/wɔːrm/' },
      { word: 'winter', meaning: '冬天', phonetic: '/ˈwɪntər/' },
    ],
  },
  '小三下': {
    name: '小三下',
    words: [
      // Module 1 Using my five senses
      { word: 'hear', meaning: '听到', phonetic: '/hɪr/' },
      { word: 'see', meaning: '看见', phonetic: '/siː/' },
      { word: 'touch', meaning: '触摸', phonetic: '/tʌtʃ/' },
      { word: 'feel', meaning: '感觉', phonetic: '/fiːl/' },
      { word: 'taste', meaning: '品尝', phonetic: '/teɪst/' },
      { word: 'smell', meaning: '闻', phonetic: '/smel/' },
      { word: 'sweet', meaning: '甜的', phonetic: '/swiːt/' },
      { word: 'sour', meaning: '酸的', phonetic: '/saʊr/' },
      { word: 'salty', meaning: '咸的', phonetic: '/ˈsɔːlti/' },
      { word: 'bitter', meaning: '苦的', phonetic: '/ˈbɪtər/' },
      { word: 'soft', meaning: '柔软的', phonetic: '/sɔːft/' },
      { word: 'hard', meaning: '坚硬的', phonetic: '/hɑːrd/' },
      { word: 'rough', meaning: '粗糙的', phonetic: '/rʌf/' },
      { word: 'smooth', meaning: '光滑的', phonetic: '/smuːð/' },
      { word: 'thick', meaning: '厚的', phonetic: '/θɪk/' },
      { word: 'thin', meaning: '薄的', phonetic: '/θɪn/' },
      // Module 2 My favourite things - Animals
      { word: 'elephant', meaning: '大象', phonetic: '/ˈelɪfənt/' },
      { word: 'monkey', meaning: '猴子', phonetic: '/ˈmʌŋki/' },
      { word: 'panda', meaning: '熊猫', phonetic: '/ˈpændə/' },
      { word: 'tiger', meaning: '老虎', phonetic: '/ˈtaɪɡər/' },
      { word: 'lion', meaning: '狮子', phonetic: '/ˈlaɪən/' },
      { word: 'bear', meaning: '熊', phonetic: '/ber/' },
      { word: 'horse', meaning: '马', phonetic: '/hɔːrs/' },
      { word: 'sheep', meaning: '绵羊', phonetic: '/ʃiːp/' },
      { word: 'chicken', meaning: '鸡', phonetic: '/ˈtʃɪkɪn/' },
      { word: 'duck', meaning: '鸭子', phonetic: '/dʌk/' },
      { word: 'pig', meaning: '猪', phonetic: '/pɪɡ/' },
      { word: 'cow', meaning: '奶牛', phonetic: '/kaʊ/' },
      // Module 2 Toys
      { word: 'toy', meaning: '玩具', phonetic: '/tɔɪ/' },
      { word: 'doll', meaning: '娃娃', phonetic: '/dɒl/' },
      { word: 'ball', meaning: '球', phonetic: '/bɔːl/' },
      { word: 'kite', meaning: '风筝', phonetic: '/kaɪt/' },
      { word: 'robot', meaning: '机器人', phonetic: '/ˈroʊbɑːt/' },
      { word: 'skateboard', meaning: '滑板', phonetic: '/ˈskeɪtbɔːrd/' },
      // Module 2 Clothes
      { word: 'hat', meaning: '帽子', phonetic: '/hæt/' },
      { word: 'scarf', meaning: '围巾', phonetic: '/skɑːrf/' },
      { word: 'glove', meaning: '手套', phonetic: '/ɡlʌv/' },
      { word: 'sock', meaning: '袜子', phonetic: '/sɑːk/' },
      { word: 'shirt', meaning: '衬衫', phonetic: '/ʃɜːrt/' },
      { word: 'T-shirt', meaning: 'T恤衫', phonetic: '/ˈtiː ʃɜːrt/' },
      { word: 'dress', meaning: '连衣裙', phonetic: '/dres/' },
      { word: 'coat', meaning: '外套', phonetic: '/koʊt/' },
      { word: 'shoe', meaning: '鞋子', phonetic: '/ʃuː/' },
      { word: 'trousers', meaning: '裤子', phonetic: '/ˈtraʊzərz/' },
      // Module 3 Shapes
      { word: 'circle', meaning: '圆形', phonetic: '/ˈsɜːrkl/' },
      { word: 'square', meaning: '正方形', phonetic: '/skwer/' },
      { word: 'triangle', meaning: '三角形', phonetic: '/ˈtraɪæŋɡl/' },
      { word: 'rectangle', meaning: '长方形', phonetic: '/ˈrektæŋɡl/' },
      { word: 'star', meaning: '星形', phonetic: '/stɑːr/' },
      { word: 'shape', meaning: '形状', phonetic: '/ʃeɪp/' },
      // Module 3 Colours
      { word: 'red', meaning: '红色的', phonetic: '/red/' },
      { word: 'blue', meaning: '蓝色的', phonetic: '/bluː/' },
      { word: 'green', meaning: '绿色的', phonetic: '/ɡriːn/' },
      { word: 'yellow', meaning: '黄色的', phonetic: '/ˈjeloʊ/' },
      { word: 'black', meaning: '黑色的', phonetic: '/blæk/' },
      { word: 'white', meaning: '白色的', phonetic: '/waɪt/' },
      { word: 'brown', meaning: '棕色的', phonetic: '/braʊn/' },
      { word: 'pink', meaning: '粉色的', phonetic: '/pɪŋk/' },
      { word: 'purple', meaning: '紫色的', phonetic: '/ˈpɜːrpl/' },
      { word: 'orange', meaning: '橙色的', phonetic: '/ˈɒrɪndʒ/' },
      // Module 3 Seasons
      { word: 'spring', meaning: '春天', phonetic: '/sprɪŋ/' },
      { word: 'summer', meaning: '夏天', phonetic: '/ˈsʌmər/' },
      { word: 'autumn', meaning: '秋天', phonetic: '/ˈɔːtəm/' },
      { word: 'winter', meaning: '冬天', phonetic: '/ˈwɪntər/' },
      { word: 'warm', meaning: '温暖的', phonetic: '/wɔːrm/' },
      { word: 'hot', meaning: '热的', phonetic: '/hɑːt/' },
      { word: 'cool', meaning: '凉爽的', phonetic: '/kuːl/' },
      { word: 'cold', meaning: '冷的', phonetic: '/koʊld/' },
      // Module 4 My body
      { word: 'head', meaning: '头', phonetic: '/hed/' },
      { word: 'shoulder', meaning: '肩膀', phonetic: '/ˈʃoʊldər/' },
      { word: 'knee', meaning: '膝盖', phonetic: '/niː/' },
      { word: 'toe', meaning: '脚趾', phonetic: '/toʊ/' },
      { word: 'arm', meaning: '手臂', phonetic: '/ɑːrm/' },
      { word: 'hand', meaning: '手', phonetic: '/hænd/' },
      { word: 'leg', meaning: '腿', phonetic: '/leɡ/' },
      { word: 'foot', meaning: '脚', phonetic: '/fʊt/' },
      // Module 4 Children's Day
      { word: 'sing', meaning: '唱歌', phonetic: '/sɪŋ/' },
      { word: 'dance', meaning: '跳舞', phonetic: '/dæns/' },
      { word: 'play', meaning: '玩', phonetic: '/pleɪ/' },
      { word: 'draw', meaning: '画画', phonetic: '/drɔː/' },
      { word: 'photo', meaning: '照片', phonetic: '/ˈfoʊtoʊ/' },
      { word: 'present', meaning: '礼物', phonetic: '/ˈpreznt/' },
      { word: 'party', meaning: '聚会', phonetic: '/ˈpɑːrti/' },
    ],
  },
  '小四上': {
    name: '小四上',
    words: [
      // Module 1 Getting to know you
      { word: 'able', meaning: '能干的', phonetic: '/ˈeɪbl/' },
      { word: 'around', meaning: '到处', phonetic: '/əˈraʊnd/' },
      { word: 'any', meaning: '任何', phonetic: '/ˈeni/' },
      { word: 'ask', meaning: '问', phonetic: '/æsk/' },
      { word: 'answer', meaning: '回答', phonetic: '/ˈænsər/' },
      { word: 'class', meaning: '班级', phonetic: '/klæs/' },
      { word: 'classmate', meaning: '同学', phonetic: '/ˈklæsmeɪt/' },
      { word: 'email', meaning: '电子邮件', phonetic: '/ˈiːmeɪl/' },
      { word: 'from', meaning: '从', phonetic: '/frʌm/' },
      { word: 'live', meaning: '居住', phonetic: '/lɪv/' },
      { word: 'name', meaning: '名字', phonetic: '/neɪm/' },
      { word: 'new', meaning: '新的', phonetic: '/njuː/' },
      { word: 'old', meaning: '旧的；年老的', phonetic: '/oʊld/' },
      { word: 'run', meaning: '跑', phonetic: '/rʌn/' },
      { word: 'sing', meaning: '唱歌', phonetic: '/sɪŋ/' },
      { word: 'swim', meaning: '游泳', phonetic: '/swɪm/' },
      { word: 'write', meaning: '写', phonetic: '/raɪt/' },
      { word: 'jump', meaning: '跳', phonetic: '/dʒʌmp/' },
      { word: 'draw', meaning: '画画', phonetic: '/drɔː/' },
      { word: 'dance', meaning: '跳舞', phonetic: '/dæns/' },
      // Module 2 Me, my family and friends
      { word: 'aunt', meaning: '阿姨', phonetic: '/ænt/' },
      { word: 'uncle', meaning: '叔叔', phonetic: '/ˈʌŋkl/' },
      { word: 'cousin', meaning: '表亲', phonetic: '/ˈkʌzn/' },
      { word: 'daughter', meaning: '女儿', phonetic: '/ˈdɔːtər/' },
      { word: 'son', meaning: '儿子', phonetic: '/sʌn/' },
      { word: 'family', meaning: '家庭', phonetic: '/ˈfæməli/' },
      { word: 'grandparent', meaning: '祖父母', phonetic: '/ˈɡrænperənt/' },
      { word: 'parent', meaning: '父（母）亲', phonetic: '/ˈperənt/' },
      { word: 'people', meaning: '人', phonetic: '/ˈpiːpl/' },
      { word: 'only', meaning: '只有', phonetic: '/ˈoʊnli/' },
      { word: 'same', meaning: '相同的', phonetic: '/seɪm/' },
      { word: 'different', meaning: '不同的', phonetic: '/ˈdɪfrənt/' },
      // Module 3 Places and activities - School
      { word: 'building', meaning: '建筑物', phonetic: '/ˈbɪldɪŋ/' },
      { word: 'computer', meaning: '电脑', phonetic: '/kəmˈpjuːtər/' },
      { word: 'floor', meaning: '楼层', phonetic: '/flɔːr/' },
      { word: 'gym', meaning: '体育馆', phonetic: '/dʒɪm/' },
      { word: 'hall', meaning: '大厅', phonetic: '/hɔːl/' },
      { word: 'library', meaning: '图书馆', phonetic: '/ˈlaɪbreri/' },
      { word: 'office', meaning: '办公室', phonetic: '/ˈɔːfɪs/' },
      { word: 'playground', meaning: '操场', phonetic: '/ˈpleɪɡraʊnd/' },
      { word: 'room', meaning: '房间', phonetic: '/ruːm/' },
      { word: 'toilet', meaning: '洗手间', phonetic: '/ˈtɔɪlət/' },
      { word: 'behind', meaning: '在…后面', phonetic: '/bɪˈhaɪnd/' },
      { word: 'beside', meaning: '在…旁边', phonetic: '/bɪˈsaɪd/' },
      { word: 'between', meaning: '在…之间', phonetic: '/bɪˈtwiːn/' },
      { word: 'under', meaning: '在…下面', phonetic: '/ˈʌndər/' },
      { word: 'above', meaning: '在…上面', phonetic: '/əˈbʌv/' },
      // Module 3 Shopping
      { word: 'buy', meaning: '买', phonetic: '/baɪ/' },
      { word: 'sell', meaning: '卖', phonetic: '/sel/' },
      { word: 'cheap', meaning: '便宜的', phonetic: '/tʃiːp/' },
      { word: 'expensive', meaning: '昂贵的', phonetic: '/ɪkˈspensɪv/' },
      { word: 'money', meaning: '钱', phonetic: '/ˈmʌni/' },
      { word: 'price', meaning: '价格', phonetic: '/praɪs/' },
      { word: 'shop', meaning: '商店', phonetic: '/ʃɑːp/' },
      { word: 'supermarket', meaning: '超市', phonetic: '/ˈsuːpərmɑːrkɪt/' },
      // Module 4 The natural world - Weather
      { word: 'weather', meaning: '天气', phonetic: '/ˈweðər/' },
      { word: 'sunny', meaning: '晴朗的', phonetic: '/ˈsʌni/' },
      { word: 'cloudy', meaning: '多云的', phonetic: '/ˈklaʊdi/' },
      { word: 'rainy', meaning: '下雨的', phonetic: '/ˈreɪni/' },
      { word: 'windy', meaning: '有风的', phonetic: '/ˈwɪndi/' },
      { word: 'snowy', meaning: '下雪的', phonetic: '/ˈsnoʊi/' },
      { word: 'foggy', meaning: '有雾的', phonetic: '/ˈfɑːɡi/' },
      { word: 'warm', meaning: '温暖的', phonetic: '/wɔːrm/' },
      { word: 'cool', meaning: '凉爽的', phonetic: '/kuːl/' },
      // Module 4 Animals
      { word: 'animal', meaning: '动物', phonetic: '/ˈænɪml/' },
      { word: 'wild', meaning: '野生的', phonetic: '/waɪld/' },
      { word: 'zoo', meaning: '动物园', phonetic: '/zuː/' },
      { word: 'forest', meaning: '森林', phonetic: '/ˈfɔːrɪst/' },
      { word: 'mountain', meaning: '山', phonetic: '/ˈmaʊntən/' },
      { word: 'river', meaning: '河流', phonetic: '/ˈrɪvər/' },
      { word: 'lake', meaning: '湖泊', phonetic: '/leɪk/' },
      // Others
      { word: 'often', meaning: '经常', phonetic: '/ˈɔːfn/' },
      { word: 'sometimes', meaning: '有时候', phonetic: '/ˈsʌmtaɪmz/' },
      { word: 'always', meaning: '总是', phonetic: '/ˈɔːlweɪz/' },
      { word: 'never', meaning: '从不', phonetic: '/ˈnevər/' },
      { word: 'usually', meaning: '通常', phonetic: '/ˈjuːʒuəli/' },
    ],
  },
  '小四下': {
    name: '小四下',
    words: [
      // Module 1 Using my five senses
      { word: 'blind', meaning: '盲的', phonetic: '/blaɪnd/' },
      { word: 'deaf', meaning: '聋的', phonetic: '/def/' },
      { word: 'sound', meaning: '声音', phonetic: '/saʊnd/' },
      { word: 'noise', meaning: '噪音', phonetic: '/nɔɪz/' },
      { word: 'loud', meaning: '吵闹的', phonetic: '/laʊd/' },
      { word: 'quiet', meaning: '安静的', phonetic: '/ˈkwaɪət/' },
      { word: 'noisy', meaning: '嘈杂的', phonetic: '/ˈnɔɪzi/' },
      { word: 'silence', meaning: '安静', phonetic: '/ˈsaɪləns/' },
      { word: 'grow', meaning: '生长', phonetic: '/ɡroʊ/' },
      { word: 'seed', meaning: '种子', phonetic: '/siːd/' },
      { word: 'leaf', meaning: '叶子', phonetic: '/liːf/' },
      { word: 'plant', meaning: '植物', phonetic: '/plænt/' },
      { word: 'water', meaning: '浇水', phonetic: '/ˈwɔːtər/' },
      // Module 2 My favourite things - Food and drinks
      { word: 'breakfast', meaning: '早餐', phonetic: '/ˈbrekfəst/' },
      { word: 'lunch', meaning: '午餐', phonetic: '/lʌntʃ/' },
      { word: 'dinner', meaning: '晚餐', phonetic: '/ˈdɪnər/' },
      { word: 'meal', meaning: '一餐', phonetic: '/miːl/' },
      { word: 'hungry', meaning: '饥饿的', phonetic: '/ˈhʌŋɡri/' },
      { word: 'thirsty', meaning: '口渴的', phonetic: '/ˈθɜːrsti/' },
      { word: 'healthy', meaning: '健康的', phonetic: '/ˈhelθi/' },
      { word: 'unhealthy', meaning: '不健康的', phonetic: '/ʌnˈhelθi/' },
      { word: 'favorite', meaning: '最喜欢的', phonetic: '/ˈfeɪvərɪt/' },
      { word: 'delicious', meaning: '美味的', phonetic: '/dɪˈlɪʃəs/' },
      { word: 'fruit', meaning: '水果', phonetic: '/fruːt/' },
      { word: 'vegetable', meaning: '蔬菜', phonetic: '/ˈvedʒtəbl/' },
      { word: 'meat', meaning: '肉', phonetic: '/miːt/' },
      { word: 'fish', meaning: '鱼', phonetic: '/fɪʃ/' },
      { word: 'chicken', meaning: '鸡肉', phonetic: '/ˈtʃɪkɪn/' },
      { word: 'beef', meaning: '牛肉', phonetic: '/biːf/' },
      { word: 'rice', meaning: '米饭', phonetic: '/raɪs/' },
      { word: 'noodles', meaning: '面条', phonetic: '/ˈnuːdlz/' },
      { word: 'bread', meaning: '面包', phonetic: '/bred/' },
      { word: 'milk', meaning: '牛奶', phonetic: '/mɪlk/' },
      { word: 'juice', meaning: '果汁', phonetic: '/dʒuːs/' },
      { word: 'tea', meaning: '茶', phonetic: '/tiː/' },
      { word: 'coffee', meaning: '咖啡', phonetic: '/ˈkɑːfi/' },
      { word: 'cake', meaning: '蛋糕', phonetic: '/keɪk/' },
      { word: 'egg', meaning: '鸡蛋', phonetic: '/eɡ/' },
      { word: 'soup', meaning: '汤', phonetic: '/suːp/' },
      // Module 2 Films
      { word: 'film', meaning: '电影', phonetic: '/fɪlm/' },
      { word: 'cinema', meaning: '电影院', phonetic: '/ˈsɪnəmə/' },
      { word: 'story', meaning: '故事', phonetic: '/ˈstɔːri/' },
      { word: 'cartoon', meaning: '卡通', phonetic: '/kɑːrˈtuːn/' },
      { word: 'interesting', meaning: '有趣的', phonetic: '/ˈɪntrəstɪŋ/' },
      { word: 'boring', meaning: '无聊的', phonetic: '/ˈbɔːrɪŋ/' },
      { word: 'exciting', meaning: '令人兴奋的', phonetic: '/ɪkˈsaɪtɪŋ/' },
      { word: 'funny', meaning: '滑稽的', phonetic: '/ˈfʌni/' },
      // Module 2 School subjects
      { word: 'subject', meaning: '科目', phonetic: '/ˈsʌbdʒɪkt/' },
      { word: 'Chinese', meaning: '语文', phonetic: '/tʃaɪˈniːz/' },
      { word: 'English', meaning: '英语', phonetic: '/ˈɪŋɡlɪʃ/' },
      { word: 'math', meaning: '数学', phonetic: '/mæθ/' },
      { word: 'science', meaning: '科学', phonetic: '/ˈsaɪəns/' },
      { word: 'music', meaning: '音乐', phonetic: '/ˈmjuːzɪk/' },
      { word: 'art', meaning: '美术', phonetic: '/ɑːrt/' },
      { word: 'PE', meaning: '体育', phonetic: '/piː iː/' },
      { word: 'lesson', meaning: '课', phonetic: '/ˈlesn/' },
      { word: 'homework', meaning: '作业', phonetic: '/ˈhoʊmwɜːrk/' },
      { word: 'study', meaning: '学习', phonetic: '/ˈstʌdi/' },
      { word: 'difficult', meaning: '困难的', phonetic: '/ˈdɪfɪkəlt/' },
      { word: 'easy', meaning: '容易的', phonetic: '/ˈiːzi/' },
      // Module 3 Signs
      { word: 'sign', meaning: '标志', phonetic: '/saɪn/' },
      { word: 'mean', meaning: '意思是', phonetic: '/miːn/' },
      { word: 'must', meaning: '必须', phonetic: '/mʌst/' },
      { word: 'should', meaning: '应该', phonetic: '/ʃʊd/' },
      { word: 'cannot', meaning: '不能', phonetic: '/ˈkænɑːt/' },
      { word: 'careful', meaning: '小心的', phonetic: '/ˈkerfl/' },
      { word: 'danger', meaning: '危险', phonetic: '/ˈdeɪndʒər/' },
      { word: 'safe', meaning: '安全的', phonetic: '/seɪf/' },
      { word: 'rule', meaning: '规则', phonetic: '/ruːl/' },
      // Module 3 Weather
      { word: 'weather', meaning: '天气', phonetic: '/ˈweðər/' },
      { word: 'temperature', meaning: '温度', phonetic: '/ˈtemprətʃər/' },
      { word: 'degree', meaning: '度', phonetic: '/dɪˈɡriː/' },
      { word: 'season', meaning: '季节', phonetic: '/ˈsiːzn/' },
      { word: 'dry', meaning: '干燥的', phonetic: '/draɪ/' },
      { word: 'wet', meaning: '潮湿的', phonetic: '/wet/' },
      // Module 3 Changes
      { word: 'change', meaning: '改变', phonetic: '/tʃeɪndʒ/' },
      { word: 'become', meaning: '变成', phonetic: '/bɪˈkʌm/' },
      { word: 'grow', meaning: '成长', phonetic: '/ɡroʊ/' },
      { word: 'turn', meaning: '变成', phonetic: '/tɜːrn/' },
      // Module 4 Museums
      { word: 'museum', meaning: '博物馆', phonetic: '/mjuːˈziːəm/' },
      { word: 'exhibition', meaning: '展览', phonetic: '/ˌeksɪˈbɪʃn/' },
      { word: 'history', meaning: '历史', phonetic: '/ˈhɪstri/' },
      { word: 'culture', meaning: '文化', phonetic: '/ˈkʌltʃər/' },
      { word: 'visit', meaning: '参观', phonetic: '/ˈvɪzɪt/' },
      // Module 4 Western holidays
      { word: 'holiday', meaning: '假日', phonetic: '/ˈhɑːlədeɪ/' },
      { word: 'Christmas', meaning: '圣诞节', phonetic: '/ˈkrɪsməs/' },
      { word: 'Halloween', meaning: '万圣节', phonetic: '/ˌhæloʊˈiːn/' },
      { word: 'Easter', meaning: '复活节', phonetic: '/ˈiːstər/' },
      { word: 'Thanksgiving', meaning: '感恩节', phonetic: '/ˌθæŋksˈɡɪvɪŋ/' },
      { word: 'celebrate', meaning: '庆祝', phonetic: '/ˈselɪbreɪt/' },
      { word: 'gift', meaning: '礼物', phonetic: '/ɡɪft/' },
      // Module 4 Story time
      { word: 'prince', meaning: '王子', phonetic: '/prɪns/' },
      { word: 'princess', meaning: '公主', phonetic: '/ˈprɪnses/' },
      { word: 'queen', meaning: '女王', phonetic: '/kwiːn/' },
      { word: 'king', meaning: '国王', phonetic: '/kɪŋ/' },
      { word: 'fairy', meaning: '仙子', phonetic: '/ˈferi/' },
      { word: 'magic', meaning: '魔法', phonetic: '/ˈmædʒɪk/' },
    ],
  },
  '小五上': {
    name: '小五上',
    words: [
      // Module 1 Getting to know you - My birthday
      { word: 'birthday', meaning: '生日', phonetic: '/ˈbɜːrθdeɪ/' },
      { word: 'begin', meaning: '开始', phonetic: '/bɪˈɡɪn/' },
      { word: 'arrive', meaning: '到达', phonetic: '/əˈraɪv/' },
      { word: 'bring', meaning: '带来', phonetic: '/brɪŋ/' },
      { word: 'dream', meaning: '梦想', phonetic: '/driːm/' },
      { word: 'favorite', meaning: '最喜欢的', phonetic: '/ˈfeɪvərɪt/' },
      { word: 'first', meaning: '第一', phonetic: '/fɜːrst/' },
      { word: 'second', meaning: '第二', phonetic: '/ˈsekənd/' },
      { word: 'third', meaning: '第三', phonetic: '/θɜːrd/' },
      { word: 'fifth', meaning: '第五', phonetic: '/fɪfθ/' },
      { word: 'sixth', meaning: '第六', phonetic: '/sɪksθ/' },
      { word: 'invitation', meaning: '请柬', phonetic: '/ˌɪnvɪˈteɪʃn/' },
      { word: 'party', meaning: '聚会', phonetic: '/ˈpɑːrti/' },
      { word: 'present', meaning: '礼物', phonetic: '/ˈpreznt/' },
      { word: 'smart', meaning: '聪明的', phonetic: '/smɑːrt/' },
      { word: 'star', meaning: '星星', phonetic: '/stɑːr/' },
      // Module 1 My way to school
      { word: 'by', meaning: '乘', phonetic: '/baɪ/' },
      { word: 'cross', meaning: '穿过', phonetic: '/krɔːs/' },
      { word: 'journey', meaning: '行程', phonetic: '/ˈdʒɜːrni/' },
      { word: 'leave', meaning: '离开', phonetic: '/liːv/' },
      { word: 'on foot', meaning: '步行', phonetic: '/ɑːn fʊt/' },
      { word: 'pavement', meaning: '人行道', phonetic: '/ˈpeɪvmənt/' },
      { word: 'taxi', meaning: '出租车', phonetic: '/ˈtæksi/' },
      { word: 'traffic light', meaning: '交通灯', phonetic: '/ˈtræfɪk laɪt/' },
      { word: 'underground', meaning: '地铁', phonetic: '/ˈʌndərɡraʊnd/' },
      { word: 'zebra crossing', meaning: '斑马线', phonetic: '/ˈziːbrə ˈkrɔːsɪŋ/' },
      // Module 1 My future
      { word: 'afraid', meaning: '害怕的', phonetic: '/əˈfreɪd/' },
      { word: 'fly', meaning: '驾驶（飞机）', phonetic: '/flaɪ/' },
      { word: 'help', meaning: '帮助', phonetic: '/help/' },
      { word: 'lifeguard', meaning: '救生员', phonetic: '/ˈlaɪfɡɑːrd/' },
      { word: 'pilot', meaning: '飞行员', phonetic: '/ˈpaɪlət/' },
      { word: 'save', meaning: '救', phonetic: '/seɪv/' },
      { word: 'sick', meaning: '生病的', phonetic: '/sɪk/' },
      { word: 'travel', meaning: '旅行', phonetic: '/ˈtrævl/' },
      { word: 'wear', meaning: '穿', phonetic: '/wer/' },
      { word: 'writer', meaning: '作家', phonetic: '/ˈraɪtər/' },
      { word: 'shop assistant', meaning: '店员', phonetic: '/ʃɑːp əˈsɪstənt/' },
      { word: 'future', meaning: '未来', phonetic: '/ˈfjuːtʃər/' },
      { word: 'good at', meaning: '擅长', phonetic: '/ɡʊd æt/' },
      // Module 2 Grandparents
      { word: 'chess', meaning: '国际象棋', phonetic: '/tʃes/' },
      { word: 'grandchild', meaning: '孙辈', phonetic: '/ˈɡræntʃaɪld/' },
      { word: 'member', meaning: '成员', phonetic: '/ˈmembər/' },
      { word: 'weekend', meaning: '周末', phonetic: '/ˈwiːkend/' },
      { word: 'twice', meaning: '两次', phonetic: '/twaɪs/' },
      { word: ' outing', meaning: '郊游', phonetic: '/ˈaʊtɪŋ/' },
      { word: 'hug', meaning: '拥抱', phonetic: '/hʌɡ/' },
      // Module 2 Friends
      { word: 'both', meaning: '两者都', phonetic: '/boʊθ/' },
      { word: 'each other', meaning: '互相', phonetic: '/iːtʃ ˈʌðər/' },
      { word: 'same', meaning: '相同的', phonetic: '/seɪm/' },
      { word: 'different', meaning: '不同的', phonetic: '/ˈdɪfrənt/' },
      { word: 'share', meaning: '分享', phonetic: '/ʃer/' },
      { word: 'together', meaning: '一起', phonetic: '/təˈɡeðər/' },
      { word: 'team', meaning: '队', phonetic: '/tiːm/' },
      // Module 2 Moving home
      { word: 'change', meaning: '改变', phonetic: '/tʃeɪndʒ/' },
      { word: 'move', meaning: '搬', phonetic: '/muːv/' },
      { word: 'enough', meaning: '足够的', phonetic: '/ɪˈnʌf/' },
      { word: 'east', meaning: '东方', phonetic: '/iːst/' },
      { word: 'west', meaning: '西方', phonetic: '/west/' },
      { word: 'north', meaning: '北方', phonetic: '/nɔːrθ/' },
      { word: 'south', meaning: '南方', phonetic: '/saʊθ/' },
      { word: 'study', meaning: '书房', phonetic: '/ˈstʌdi/' },
      { word: 'kitchen', meaning: '厨房', phonetic: '/ˈkɪtʃɪn/' },
      { word: 'bedroom', meaning: '卧室', phonetic: '/ˈbedruːm/' },
      { word: 'bathroom', meaning: '浴室', phonetic: '/ˈbæθruːm/' },
      { word: 'living room', meaning: '客厅', phonetic: '/ˈlɪvɪŋ ruːm/' },
      { word: 'dining room', meaning: '餐厅', phonetic: '/ˈdaɪnɪŋ ruːm/' },
      { word: 'garden', meaning: '花园', phonetic: '/ˈɡɑːrdn/' },
      { word: 'balcony', meaning: '阳台', phonetic: '/ˈbælkəni/' },
      // Module 3 Around the city
      { word: 'along', meaning: '沿着', phonetic: '/əˈlɔːŋ/' },
      { word: 'between', meaning: '在…之间', phonetic: '/bɪˈtwiːn/' },
      { word: 'city', meaning: '城市', phonetic: '/ˈsɪti/' },
      { word: 'hospital', meaning: '医院', phonetic: '/ˈhɑːspɪtl/' },
      { word: 'museum', meaning: '博物馆', phonetic: '/mjuːˈziːəm/' },
      { word: 'post office', meaning: '邮局', phonetic: '/poʊst ˈɔːfɪs/' },
      { word: 'restaurant', meaning: '餐厅', phonetic: '/ˈrestrɒnt/' },
      { word: 'street', meaning: '街道', phonetic: '/striːt/' },
      { word: 'turn left', meaning: '左转', phonetic: '/tɜːrn left/' },
      { word: 'turn right', meaning: '右转', phonetic: '/tɜːrn raɪt/' },
      { word: 'straight', meaning: '直行', phonetic: '/streɪt/' },
      // Module 3 Buying new clothes
      { word: 'clothes', meaning: '衣服', phonetic: '/kloʊðz/' },
      { word: 'size', meaning: '尺码', phonetic: '/saɪz/' },
      { word: 'try on', meaning: '试穿', phonetic: '/traɪ ɑːn/' },
      { word: 'fit', meaning: '合身', phonetic: '/fɪt/' },
      { word: 'jacket', meaning: '夹克', phonetic: '/ˈdʒækɪt/' },
      { word: 'skirt', meaning: '裙子', phonetic: '/skɜːrt/' },
      { word: 'sweater', meaning: '毛衣', phonetic: '/ˈswetər/' },
      { word: 'trousers', meaning: '裤子', phonetic: '/ˈtraʊzərz/' },
      // Module 3 Seeing the doctor
      { word: 'doctor', meaning: '医生', phonetic: '/ˈdɑːktər/' },
      { word: 'medicine', meaning: '药', phonetic: '/ˈmedɪsn/' },
      { word: 'headache', meaning: '头痛', phonetic: '/ˈhedeɪk/' },
      { word: 'fever', meaning: '发烧', phonetic: '/ˈfiːvər/' },
      { word: 'cold', meaning: '感冒', phonetic: '/koʊld/' },
      { word: 'cough', meaning: '咳嗽', phonetic: '/kɔːf/' },
      { word: 'toothache', meaning: '牙痛', phonetic: '/ˈtuːθeɪk/' },
      { word: 'health', meaning: '健康', phonetic: '/helθ/' },
      { word: 'rest', meaning: '休息', phonetic: '/rest/' },
      // Module 4 Water
      { word: 'water', meaning: '水', phonetic: '/ˈwɔːtər/' },
      { word: 'use', meaning: '使用', phonetic: '/juːz/' },
      { word: 'waste', meaning: '浪费', phonetic: '/weɪst/' },
      { word: 'save', meaning: '节约', phonetic: '/seɪv/' },
      { word: 'tap', meaning: '水龙头', phonetic: '/tæp/' },
      { word: 'drop', meaning: '滴', phonetic: '/drɑːp/' },
      { word: 'rain', meaning: '雨', phonetic: '/reɪn/' },
      { word: 'cloud', meaning: '云', phonetic: '/klaʊd/' },
      { word: 'river', meaning: '河流', phonetic: '/ˈrɪvər/' },
      { word: 'sea', meaning: '海', phonetic: '/siː/' },
      // Module 4 Wind
      { word: 'wind', meaning: '风', phonetic: '/wɪnd/' },
      { word: 'blow', meaning: '吹', phonetic: '/bloʊ/' },
      { word: 'gently', meaning: '轻轻地', phonetic: '/ˈdʒentli/' },
      { word: 'strongly', meaning: '猛烈地', phonetic: '/ˈstrɔːŋli/' },
      { word: 'quickly', meaning: '快速地', phonetic: '/ˈkwɪkli/' },
      { word: 'slowly', meaning: '慢慢地', phonetic: '/ˈsloʊli/' },
      // Module 4 Fire
      { word: 'fire', meaning: '火', phonetic: '/faɪər/' },
      { word: 'burn', meaning: '燃烧', phonetic: '/bɜːrn/' },
      { word: 'careful', meaning: '小心的', phonetic: '/ˈkerfl/' },
      { word: 'dangerous', meaning: '危险的', phonetic: '/ˈdeɪndʒərəs/' },
      { word: 'match', meaning: '火柴', phonetic: '/mætʃ/' },
      { word: 'heat', meaning: '热', phonetic: '/hiːt/' },
      { word: 'smoke', meaning: '烟', phonetic: '/smoʊk/' },
    ],
  },
  '小五下': {
    name: '小五下',
    words: [
      // Module 1 Using my five senses
      { word: 'mess', meaning: '杂乱', phonetic: '/mes/' },
      { word: 'tidy', meaning: '整洁的', phonetic: '/ˈtaɪdi/' },
      { word: 'magic', meaning: '魔法', phonetic: '/ˈmædʒɪk/' },
      { word: 'stone', meaning: '石头', phonetic: '/stoʊn/' },
      { word: 'hard', meaning: '坚硬的', phonetic: '/hɑːrd/' },
      { word: 'rough', meaning: '粗糙的', phonetic: '/rʌf/' },
      { word: 'smooth', meaning: '光滑的', phonetic: '/smuːð/' },
      { word: 'soft', meaning: '柔软的', phonetic: '/sɔːft/' },
      { word: 'shape', meaning: '形状', phonetic: '/ʃeɪp/' },
      { word: 'cotton', meaning: '棉花', phonetic: '/ˈkɑːtn/' },
      { word: 'wool', meaning: '羊毛', phonetic: '/wʊl/' },
      { word: 'wood', meaning: '木头', phonetic: '/wʊd/' },
      { word: 'metal', meaning: '金属', phonetic: '/ˈmetl/' },
      { word: 'glass', meaning: '玻璃', phonetic: '/ɡlæs/' },
      { word: 'paper', meaning: '纸', phonetic: '/ˈpeɪpər/' },
      // Module 1 Watch it grow
      { word: 'butterfly', meaning: '蝴蝶', phonetic: '/ˈbʌtərflaɪ/' },
      { word: 'caterpillar', meaning: '毛毛虫', phonetic: '/ˈkætərpɪlər/' },
      { word: 'cocoon', meaning: '茧', phonetic: '/kəˈkuːn/' },
      { word: 'egg', meaning: '蛋', phonetic: '/eɡ/' },
      { word: 'insect', meaning: '昆虫', phonetic: '/ˈɪnsekt/' },
      { word: 'tadpole', meaning: '蝌蚪', phonetic: '/ˈtædpoʊl/' },
      { word: 'frog', meaning: '青蛙', phonetic: '/frɑːɡ/' },
      { word: 'chick', meaning: '小鸡', phonetic: '/tʃɪk/' },
      { word: 'hen', meaning: '母鸡', phonetic: '/hen/' },
      { word: 'duckling', meaning: '小鸭', phonetic: '/ˈdʌklɪŋ/' },
      { word: 'duck', meaning: '鸭子', phonetic: '/dʌk/' },
      { word: 'puppy', meaning: '小狗', phonetic: '/ˈpʌpi/' },
      { word: 'kitten', meaning: '小猫', phonetic: '/ˈkɪtn/' },
      { word: 'grow', meaning: '生长', phonetic: '/ɡroʊ/' },
      { word: 'become', meaning: '变成', phonetic: '/bɪˈkʌm/' },
      { word: 'born', meaning: '出生', phonetic: '/bɔːrn/' },
      // Module 1 How noisy
      { word: 'noise', meaning: '噪音', phonetic: '/nɔɪz/' },
      { word: 'noisy', meaning: '嘈杂的', phonetic: '/ˈnɔɪzi/' },
      { word: 'loud', meaning: '大声的', phonetic: '/laʊd/' },
      { word: 'quiet', meaning: '安静的', phonetic: '/ˈkwaɪət/' },
      { word: 'bell', meaning: '铃', phonetic: '/bel/' },
      { word: 'drill', meaning: '钻头', phonetic: '/drɪl/' },
      { word: 'engine', meaning: '引擎', phonetic: '/ˈendʒɪn/' },
      { word: 'lorry', meaning: '卡车', phonetic: '/ˈlɔːri/' },
      { word: 'motorbike', meaning: '摩托车', phonetic: '/ˈmoʊtərbaɪk/' },
      // Module 2 Food and drinks
      { word: 'sausage', meaning: '香肠', phonetic: '/ˈsɔːsɪdʒ/' },
      { word: 'salad', meaning: '沙拉', phonetic: '/ˈsæləd/' },
      { word: 'sandwich', meaning: '三明治', phonetic: '/ˈsænwɪtʃ/' },
      { word: 'yogurt', meaning: '酸奶', phonetic: '/ˈjoʊɡərt/' },
      { word: 'cheese', meaning: '奶酪', phonetic: '/tʃiːz/' },
      { word: 'butter', meaning: '黄油', phonetic: '/ˈbʌtər/' },
      { word: 'sugar', meaning: '糖', phonetic: '/ˈʃʊɡər/' },
      { word: 'salt', meaning: '盐', phonetic: '/sɔːlt/' },
      { word: 'pepper', meaning: '胡椒', phonetic: '/ˈpepər/' },
      { word: 'flour', meaning: '面粉', phonetic: '/ˈflaʊər/' },
      { word: 'oil', meaning: '油', phonetic: '/ɔɪl/' },
      { word: 'chocolate', meaning: '巧克力', phonetic: '/ˈtʃɑːklət/' },
      { word: 'biscuit', meaning: '饼干', phonetic: '/ˈbɪskɪt/' },
      { word: 'ice cream', meaning: '冰淇淋', phonetic: '/aɪs kriːm/' },
      { word: 'pineapple', meaning: '菠萝', phonetic: '/ˈpaɪnæpl/' },
      { word: 'strawberry', meaning: '草莓', phonetic: '/ˈstrɔːberi/' },
      { word: 'grape', meaning: '葡萄', phonetic: '/ɡreɪp/' },
      { word: 'watermelon', meaning: '西瓜', phonetic: '/ˈwɔːtərmelən/' },
      { word: 'coconut', meaning: '椰子', phonetic: '/ˈkoʊkənʌt/' },
      // Module 2 Films
      { word: 'actor', meaning: '演员', phonetic: '/ˈæktər/' },
      { word: 'actress', meaning: '女演员', phonetic: '/ˈæktrəs/' },
      { word: 'director', meaning: '导演', phonetic: '/dəˈrektər/' },
      { word: 'hero', meaning: '英雄', phonetic: '/ˈhɪroʊ/' },
      { word: 'villain', meaning: '坏人', phonetic: '/ˈvɪlən/' },
      { word: 'prince', meaning: '王子', phonetic: '/prɪns/' },
      { word: 'princess', meaning: '公主', phonetic: '/ˈprɪnses/' },
      { word: 'fairy tale', meaning: '童话', phonetic: '/ˈferi teɪl/' },
      { word: 'adventure', meaning: '冒险', phonetic: '/ədˈventʃər/' },
      // Module 3 Signs / Rules
      { word: 'must', meaning: '必须', phonetic: '/mʌst/' },
      { word: 'should', meaning: '应该', phonetic: '/ʃʊd/' },
      { word: 'must not', meaning: '不可以', phonetic: '/mʌst nɑːt/' },
      { word: 'do not', meaning: '不要', phonetic: '/duː nɑːt/' },
      { word: 'litter', meaning: '乱扔垃圾', phonetic: '/ˈlɪtər/' },
      { word: 'smoke', meaning: '吸烟', phonetic: '/smoʊk/' },
      { word: 'swim', meaning: '游泳', phonetic: '/swɪm/' },
      { word: 'run', meaning: '跑', phonetic: '/rʌn/' },
      { word: 'climb', meaning: '攀爬', phonetic: '/klaɪm/' },
      { word: 'pick', meaning: '摘', phonetic: '/pɪk/' },
      { word: 'throw', meaning: '扔', phonetic: '/θroʊ/' },
      { word: 'catch', meaning: '接住', phonetic: '/kætʃ/' },
      // Module 3 Weather
      { word: 'weather', meaning: '天气', phonetic: '/ˈweðər/' },
      { word: 'sunny', meaning: '晴朗的', phonetic: '/ˈsʌni/' },
      { word: 'rainy', meaning: '下雨的', phonetic: '/ˈreɪni/' },
      { word: 'cloudy', meaning: '多云的', phonetic: '/ˈklaʊdi/' },
      { word: 'windy', meaning: '有风的', phonetic: '/ˈwɪndi/' },
      { word: 'storm', meaning: '暴风雨', phonetic: '/stɔːrm/' },
      { word: 'typhoon', meaning: '台风', phonetic: '/taɪˈfuːn/' },
      { word: 'flood', meaning: '洪水', phonetic: '/flʌd/' },
      { word: 'drought', meaning: '干旱', phonetic: '/draʊt/' },
      // Module 4 Museums
      { word: 'insect', meaning: '昆虫', phonetic: '/ˈɪnsekt/' },
      { word: 'dinosaur', meaning: '恐龙', phonetic: '/ˈdaɪnəsɔːr/' },
      { word: 'fossil', meaning: '化石', phonetic: '/ˈfɑːsl/' },
      { word: 'robot', meaning: '机器人', phonetic: '/ˈroʊbɑːt/' },
      { word: 'model', meaning: '模型', phonetic: '/ˈmɑːdl/' },
      { word: 'science', meaning: '科学', phonetic: '/ˈsaɪəns/' },
      { word: 'technology', meaning: '技术', phonetic: '/tekˈnɑːlədʒi/' },
      { word: 'nature', meaning: '自然', phonetic: '/ˈneɪtʃər/' },
      // Module 4 Story time
      { word: 'character', meaning: '角色', phonetic: '/ˈkerɪktər/' },
      { word: 'beginning', meaning: '开头', phonetic: '/bɪˈɡɪnɪŋ/' },
      { word: 'middle', meaning: '中间', phonetic: '/ˈmɪdl/' },
      { word: 'end', meaning: '结尾', phonetic: '/end/' },
      { word: 'plot', meaning: '情节', phonetic: '/plɑːt/' },
      { word: 'setting', meaning: '背景', phonetic: '/ˈsetɪŋ/' },
      { word: 'problem', meaning: '问题', phonetic: '/ˈprɑːbləm/' },
      { word: 'solution', meaning: '解决办法', phonetic: '/səˈluːʃn/' },
    ],
  },
  '小六上': {
    name: '小六上',
    words: [
      // Module 1 Getting to know each other - Growing up
      { word: 'month', meaning: '月份', phonetic: '/mʌnθ/' },
      { word: 'year', meaning: '年', phonetic: '/jɪr/' },
      { word: 'cute', meaning: '可爱的', phonetic: '/kjuːt/' },
      { word: 'pretty', meaning: '漂亮的', phonetic: '/ˈprɪti/' },
      { word: 'handsome', meaning: '帅气的', phonetic: '/ˈhænsəm/' },
      { word: 'tall', meaning: '高的', phonetic: '/tɔːl/' },
      { word: 'short', meaning: '矮的', phonetic: '/ʃɔːrt/' },
      { word: 'weight', meaning: '体重', phonetic: '/weɪt/' },
      { word: 'height', meaning: '身高', phonetic: '/haɪt/' },
      { word: 'grow up', meaning: '长大', phonetic: '/ɡroʊ ʌp/' },
      { word: 'primary school', meaning: '小学', phonetic: '/ˈpraɪmeri skuːl/' },
      { word: 'junior high school', meaning: '初中', phonetic: '/ˈdʒuːnjər haɪ skuːl/' },
      // Module 1 E-friends
      { word: 'country', meaning: '国家', phonetic: '/ˈkʌntri/' },
      { word: 'hobby', meaning: '爱好', phonetic: '/ˈhɑːbi/' },
      { word: 'age', meaning: '年龄', phonetic: '/eɪdʒ/' },
      { word: 'email', meaning: '电子邮件', phonetic: '/ˈiːmeɪl/' },
      { word: 'e-friend', meaning: '网友', phonetic: '/iː frend/' },
      { word: 'language', meaning: '语言', phonetic: '/ˈlæŋɡwɪdʒ/' },
      { word: 'yourself', meaning: '你自己', phonetic: '/jɔːrˈself/' },
      { word: 'themselves', meaning: '他们自己', phonetic: '/ðəmˈselvz/' },
      { word: 'foreign', meaning: '外国的', phonetic: '/ˈfɔːrən/' },
      { word: 'Germany', meaning: '德国', phonetic: '/ˈdʒɜːrməni/' },
      { word: 'Australia', meaning: '澳大利亚', phonetic: '/ɔːˈstreɪliə/' },
      { word: 'Canada', meaning: '加拿大', phonetic: '/ˈkænədə/' },
      { word: 'Japan', meaning: '日本', phonetic: '/dʒəˈpæn/' },
      { word: 'UK', meaning: '英国', phonetic: '/juː keɪ/' },
      { word: 'US', meaning: '美国', phonetic: '/juː es/' },
      // Module 1 Holidays
      { word: 'holiday', meaning: '假期', phonetic: '/ˈhɑːlədeɪ/' },
      { word: 'vacation', meaning: '假期', phonetic: '/veɪˈkeɪʃn/' },
      { word: 'beach', meaning: '海滩', phonetic: '/biːtʃ/' },
      { word: 'island', meaning: '岛屿', phonetic: '/ˈaɪlənd/' },
      { word: 'swimming', meaning: '游泳', phonetic: '/ˈswɪmɪŋ/' },
      { word: 'surfing', meaning: '冲浪', phonetic: '/ˈsɜːrfɪŋ/' },
      { word: 'sailing', meaning: '帆船', phonetic: '/ˈseɪlɪŋ/' },
      { word: 'diving', meaning: '潜水', phonetic: '/ˈdaɪvɪŋ/' },
      { word: 'hiking', meaning: '远足', phonetic: '/ˈhaɪkɪŋ/' },
      { word: 'camping', meaning: '露营', phonetic: '/ˈkæmpɪŋ/' },
      { word: 'fishing', meaning: '钓鱼', phonetic: '/ˈfɪʃɪŋ/' },
      { word: 'travel', meaning: '旅行', phonetic: '/ˈtrævl/' },
      { word: 'trip', meaning: '旅行', phonetic: '/trɪp/' },
      { word: 'photo', meaning: '照片', phonetic: '/ˈfoʊtoʊ/' },
      { word: 'camera', meaning: '照相机', phonetic: '/ˈkæmərə/' },
      { word: 'souvenir', meaning: '纪念品', phonetic: '/ˌsuːvəˈnɪr/' },
      // Module 2 Work and play - Art
      { word: 'paint', meaning: '绘画', phonetic: '/peɪnt/' },
      { word: 'painting', meaning: '画作', phonetic: '/ˈpeɪntɪŋ/' },
      { word: 'artist', meaning: '艺术家', phonetic: '/ˈɑːrtɪst/' },
      { word: 'drawing', meaning: '素描', phonetic: '/ˈdrɔːɪŋ/' },
      { word: 'scissors', meaning: '剪刀', phonetic: '/ˈsɪzərz/' },
      { word: 'glue', meaning: '胶水', phonetic: '/ɡluː/' },
      { word: 'brush', meaning: '画笔', phonetic: '/brʌʃ/' },
      { word: 'colour', meaning: '颜色', phonetic: '/ˈkʌlər/' },
      { word: 'ink', meaning: '墨水', phonetic: '/ɪŋk/' },
      { word: 'craft', meaning: '手艺', phonetic: '/kræft/' },
      // Module 2 Crafts
      { word: 'tool', meaning: '工具', phonetic: '/tuːl/' },
      { word: 'material', meaning: '材料', phonetic: '/məˈtɪriəl/' },
      { word: 'create', meaning: '创造', phonetic: '/kriˈeɪt/' },
      { word: 'design', meaning: '设计', phonetic: '/dɪˈzaɪn/' },
      { word: 'build', meaning: '建造', phonetic: '/bɪld/' },
      { word: 'make', meaning: '制作', phonetic: '/meɪk/' },
      { word: 'decorate', meaning: '装饰', phonetic: '/ˈdekəreɪt/' },
      { word: 'cut', meaning: '剪', phonetic: '/kʌt/' },
      { word: 'fold', meaning: '折叠', phonetic: '/foʊld/' },
      { word: 'stick', meaning: '粘贴', phonetic: '/stɪk/' },
      { word: 'shape', meaning: '形状', phonetic: '/ʃeɪp/' },
      { word: 'pattern', meaning: '图案', phonetic: '/ˈpætərn/' },
      // Module 2 PE lessons
      { word: 'sport', meaning: '运动', phonetic: '/spɔːrt/' },
      { word: 'exercise', meaning: '锻炼', phonetic: '/ˈeksərsaɪz/' },
      { word: 'race', meaning: '比赛', phonetic: '/reɪs/' },
      { word: 'long jump', meaning: '跳远', phonetic: '/lɔːŋ dʒʌmp/' },
      { word: 'high jump', meaning: '跳高', phonetic: '/haɪ dʒʌmp/' },
      { word: 'running', meaning: '跑步', phonetic: '/ˈrʌnɪŋ/' },
      { word: 'swimming', meaning: '游泳', phonetic: '/ˈswɪmɪŋ/' },
      { word: 'basketball', meaning: '篮球', phonetic: '/ˈbæskɪtbɔːl/' },
      { word: 'football', meaning: '足球', phonetic: '/ˈfʊtbɔːl/' },
      { word: 'volleyball', meaning: '排球', phonetic: '/ˈvɑːlibɔːl/' },
      { word: 'badminton', meaning: '羽毛球', phonetic: '/ˈbædmɪntən/' },
      { word: 'table tennis', meaning: '乒乓球', phonetic: '/ˈteɪbl ˈtenɪs/' },
      { word: 'win', meaning: '赢', phonetic: '/wɪn/' },
      { word: 'lose', meaning: '输', phonetic: '/luːz/' },
      { word: 'team', meaning: '队', phonetic: '/tiːm/' },
      { word: 'player', meaning: '选手', phonetic: '/ˈpleɪər/' },
      { word: 'coach', meaning: '教练', phonetic: '/koʊtʃ/' },
      { word: 'swimsuit', meaning: '泳衣', phonetic: '/ˈswɪmsuːt/' },
      { word: 'goggles', meaning: '护目镜', phonetic: '/ˈɡɑːɡlz/' },
      { word: 'cap', meaning: '帽子', phonetic: '/kæp/' },
      // Module 3 Helping others
      { word: 'help', meaning: '帮助', phonetic: '/help/' },
      { word: 'kind', meaning: '善良的', phonetic: '/kaɪnd/' },
      { word: 'polite', meaning: '有礼貌的', phonetic: '/pəˈlaɪt/' },
      { word: 'brave', meaning: '勇敢的', phonetic: '/breɪv/' },
      { word: 'honest', meaning: '诚实的', phonetic: '/ˈɑːnɪst/' },
      { word: 'patient', meaning: '耐心的', phonetic: '/ˈpeɪʃnt/' },
      { word: 'friendly', meaning: '友好的', phonetic: '/ˈfrendli/' },
      { word: 'generous', meaning: '慷慨的', phonetic: '/ˈdʒenərəs/' },
      { word: 'careful', meaning: '仔细的', phonetic: '/ˈkerfl/' },
      { word: 'cheerful', meaning: '快乐的', phonetic: '/ˈtʃɪrfl/' },
      { word: 'rude', meaning: '粗鲁的', phonetic: '/ruːd/' },
      { word: 'cruel', meaning: '残忍的', phonetic: '/ˈkruːəl/' },
      // Module 3 Reading signs
      { word: 'sign', meaning: '标志', phonetic: '/saɪn/' },
      { word: 'meaning', meaning: '意思', phonetic: '/ˈmiːnɪŋ/' },
      { word: 'direction', meaning: '方向', phonetic: '/dəˈrekʃn/' },
      { word: 'entrance', meaning: '入口', phonetic: '/ˈentrəns/' },
      { word: 'exit', meaning: '出口', phonetic: '/ˈeksɪt/' },
      { word: 'information', meaning: '信息', phonetic: '/ˌɪnfərˈmeɪʃn/' },
      { word: 'warning', meaning: '警告', phonetic: '/ˈwɔːrnɪŋ/' },
      // Module 3 Reusing things
      { word: 'reuse', meaning: '再利用', phonetic: '/riːˈjuːz/' },
      { word: 'recycle', meaning: '回收', phonetic: '/riːˈsaɪkl/' },
      { word: 'reduce', meaning: '减少', phonetic: '/rɪˈduːs/' },
      { word: 'waste', meaning: '浪费', phonetic: '/weɪst/' },
      { word: 'plastic', meaning: '塑料', phonetic: '/ˈplæstɪk/' },
      { word: 'bottle', meaning: '瓶子', phonetic: '/ˈbɑːtl/' },
      { word: 'can', meaning: '罐', phonetic: '/kæn/' },
      { word: 'paper', meaning: '纸', phonetic: '/ˈpeɪpər/' },
      { word: 'envelope', meaning: '信封', phonetic: '/ˈenvəloʊp/' },
      { word: 'rubbish', meaning: '垃圾', phonetic: '/ˈrʌbɪʃ/' },
      // Module 4 Great storybooks
      { word: 'storybook', meaning: '故事书', phonetic: '/ˈstɔːribʊk/' },
      { word: 'fairy tale', meaning: '童话', phonetic: '/ˈferi teɪl/' },
      { word: 'adventure', meaning: '冒险', phonetic: '/ədˈventʃər/' },
      { word: 'legend', meaning: '传说', phonetic: '/ˈledʒənd/' },
      { word: 'fable', meaning: '寓言', phonetic: '/ˈfeɪbl/' },
      { word: 'myth', meaning: '神话', phonetic: '/mɪθ/' },
      { word: 'character', meaning: '角色', phonetic: '/ˈkerɪktər/' },
      { word: 'hero', meaning: '英雄', phonetic: '/ˈhɪroʊ/' },
      // Module 4 Western festivals
      { word: 'Christmas', meaning: '圣诞节', phonetic: '/ˈkrɪsməs/' },
      { word: 'Halloween', meaning: '万圣节', phonetic: '/ˌhæloʊˈiːn/' },
      { word: 'Easter', meaning: '复活节', phonetic: '/ˈiːstər/' },
      { word: 'Thanksgiving', meaning: '感恩节', phonetic: '/ˌθæŋksˈɡɪvɪŋ/' },
      { word: 'Valentine', meaning: '情人节', phonetic: '/ˈvæləntaɪn/' },
      { word: 'turkey', meaning: '火鸡', phonetic: '/ˈtɜːrki/' },
      { word: 'pumpkin', meaning: '南瓜', phonetic: '/ˈpʌmpkɪn/' },
      // Module 4 The five peas
      { word: 'pea', meaning: '豌豆', phonetic: '/piː/' },
      { word: 'pod', meaning: '豆荚', phonetic: '/pɑːd/' },
      { word: 'shoot', meaning: '射击', phonetic: '/ʃuːt/' },
      { word: 'roof', meaning: '屋顶', phonetic: '/ruːf/' },
      { word: 'pigeon', meaning: '鸽子', phonetic: '/ˈpɪdʒɪn/' },
    ],
  },
  '小六下': {
    name: '小六下',
    words: [
      // Module 1 Changes and differences - You and me
      { word: 'centimetre', meaning: '厘米', phonetic: '/ˈsentɪmiːtər/' },
      { word: 'kilogram', meaning: '千克', phonetic: '/ˈkɪləɡræm/' },
      { word: 'weigh', meaning: '称重', phonetic: '/weɪ/' },
      { word: 'height', meaning: '身高', phonetic: '/haɪt/' },
      { word: 'weight', meaning: '体重', phonetic: '/weɪt/' },
      { word: 'difference', meaning: '不同', phonetic: '/ˈdɪfrəns/' },
      { word: 'similar', meaning: '相似的', phonetic: '/ˈsɪmələr/' },
      { word: 'compare', meaning: '比较', phonetic: '/kəmˈper/' },
      { word: 'downtown', meaning: '市中心', phonetic: '/ˌdaʊnˈtaʊn/' },
      { word: 'suburb', meaning: '郊区', phonetic: '/ˈsʌbɜːrb/' },
      { word: 'countryside', meaning: '乡村', phonetic: '/ˈkʌntrisaɪd/' },
      // Module 1 Changes in our lives
      { word: 'past', meaning: '过去', phonetic: '/pæst/' },
      { word: 'present', meaning: '现在', phonetic: '/ˈpreznt/' },
      { word: 'future', meaning: '未来', phonetic: '/ˈfjuːtʃər/' },
      { word: 'change', meaning: '变化', phonetic: '/tʃeɪndʒ/' },
      { word: 'invention', meaning: '发明', phonetic: '/ɪnˈvenʃn/' },
      { word: 'machine', meaning: '机器', phonetic: '/məˈʃiːn/' },
      { word: 'comfortable', meaning: '舒适的', phonetic: '/ˈkʌmftəbl/' },
      { word: 'convenient', meaning: '方便的', phonetic: '/kənˈviːniənt/' },
      { word: 'traditional', meaning: '传统的', phonetic: '/trəˈdɪʃənl/' },
      { word: 'modern', meaning: '现代的', phonetic: '/ˈmɑːdərn/' },
      { word: 'digital', meaning: '数字的', phonetic: '/ˈdɪdʒɪtl/' },
      { word: 'electronic', meaning: '电子的', phonetic: '/ɪˌlekˈtrɑːnɪk/' },
      { word: 'mobile phone', meaning: '手机', phonetic: '/ˈmoʊbl foʊn/' },
      { word: 'computer', meaning: '电脑', phonetic: '/kəmˈpjuːtər/' },
      { word: 'Internet', meaning: '互联网', phonetic: '/ˈɪntərnet/' },
      // Module 1 Our school in the future
      { word: 'robot', meaning: '机器人', phonetic: '/ˈroʊbɑːt/' },
      { word: 'online', meaning: '在线的', phonetic: '/ˈɑːnlaɪn/' },
      { word: 'virtual', meaning: '虚拟的', phonetic: '/ˈvɜːrtʃuəl/' },
      { word: 'lesson', meaning: '课程', phonetic: '/ˈlesn/' },
      { word: 'subject', meaning: '科目', phonetic: '/ˈsʌbdʒɪkt/' },
      { word: 'homework', meaning: '作业', phonetic: '/ˈhoʊmwɜːrk/' },
      { word: 'examination', meaning: '考试', phonetic: '/ɪɡˌzæmɪˈneɪʃn/' },
      { word: 'graduate', meaning: '毕业', phonetic: '/ˈɡrædʒueɪt/' },
      // Module 2 Art
      { word: 'oil painting', meaning: '油画', phonetic: '/ɔɪl ˈpeɪntɪŋ/' },
      { word: 'Chinese ink painting', meaning: '水墨画', phonetic: '/tʃaɪˈniːz ɪŋk ˈpeɪntɪŋ/' },
      { word: 'portrait', meaning: '肖像', phonetic: '/ˈpɔːrtrət/' },
      { word: 'landscape', meaning: '风景画', phonetic: '/ˈlændskeɪp/' },
      { word: 'still life', meaning: '静物画', phonetic: '/stɪl laɪf/' },
      { word: 'gallery', meaning: '画廊', phonetic: '/ˈɡæləri/' },
      { word: 'exhibition', meaning: '展览', phonetic: '/ˌeksɪˈbɪʃn/' },
      { word: 'sculpture', meaning: '雕塑', phonetic: '/ˈskʌlptʃər/' },
      // Module 2 Crafts
      { word: 'sew', meaning: '缝', phonetic: '/soʊ/' },
      { word: 'needle', meaning: '针', phonetic: '/ˈniːdl/' },
      { word: 'thread', meaning: '线', phonetic: '/θred/' },
      { word: 'fabric', meaning: '布料', phonetic: '/ˈfæbrɪk/' },
      { word: 'leather', meaning: '皮革', phonetic: '/ˈleðər/' },
      { word: 'wood', meaning: '木头', phonetic: '/wʊd/' },
      { word: 'clay', meaning: '黏土', phonetic: '/kleɪ/' },
      { word: 'pottery', meaning: '陶器', phonetic: '/ˈpɑːtəri/' },
      // Module 2 PE lessons
      { word: 'long jump', meaning: '跳远', phonetic: '/lɔːŋ dʒʌmp/' },
      { word: 'high jump', meaning: '跳高', phonetic: '/haɪ dʒʌmp/' },
      { word: 'long race', meaning: '长跑', phonetic: '/lɔːŋ reɪs/' },
      { word: 'short race', meaning: '短跑', phonetic: '/ʃɔːrt reɪs/' },
      { word: 'throw', meaning: '投掷', phonetic: '/θroʊ/' },
      { word: 'catch', meaning: '接住', phonetic: '/kætʃ/' },
      { word: 'hit', meaning: '击打', phonetic: '/hɪt/' },
      { word: 'kick', meaning: '踢', phonetic: '/kɪk/' },
      { word: 'pass', meaning: '传递', phonetic: '/pæs/' },
      // Module 3 Windy weather
      { word: 'windy', meaning: '有风的', phonetic: '/ˈwɪndi/' },
      { word: 'cloudy', meaning: '多云的', phonetic: '/ˈklaʊdi/' },
      { word: 'rainy', meaning: '下雨的', phonetic: '/ˈreɪni/' },
      { word: 'sunny', meaning: '晴朗的', phonetic: '/ˈsʌni/' },
      { word: 'foggy', meaning: '有雾的', phonetic: '/ˈfɑːɡi/' },
      { word: 'storm', meaning: '暴风雨', phonetic: '/stɔːrm/' },
      { word: 'typhoon', meaning: '台风', phonetic: '/taɪˈfuːn/' },
      { word: 'heavy', meaning: '大量的', phonetic: '/ˈhevi/' },
      { word: 'strong', meaning: '强烈的', phonetic: '/strɔːŋ/' },
      { word: 'gentle', meaning: '温和的', phonetic: '/ˈdʒentl/' },
      { word: 'blow', meaning: '吹', phonetic: '/bloʊ/' },
      // Module 3 Sea water and rain water
      { word: 'ocean', meaning: '海洋', phonetic: '/ˈoʊʃn/' },
      { word: 'sea', meaning: '海', phonetic: '/siː/' },
      { word: 'rain water', meaning: '雨水', phonetic: '/reɪn ˈwɔːtər/' },
      { word: 'fresh water', meaning: '淡水', phonetic: '/freʃ ˈwɔːtər/' },
      { word: 'salt water', meaning: '咸水', phonetic: '/sɔːlt ˈwɔːtər/' },
      { word: 'save', meaning: '节约', phonetic: '/seɪv/' },
      { word: 'waste', meaning: '浪费', phonetic: '/weɪst/' },
      { word: 'pollute', meaning: '污染', phonetic: '/pəˈluːt/' },
      { word: 'clean', meaning: '清洁的', phonetic: '/kliːn/' },
      { word: 'dirty', meaning: '脏的', phonetic: '/ˈdɜːrti/' },
      { word: 'whale', meaning: '鲸鱼', phonetic: '/weɪl/' },
      { word: 'dolphin', meaning: '海豚', phonetic: '/ˈdɑːlfɪn/' },
      { word: 'shark', meaning: '鲨鱼', phonetic: '/ʃɑːrk/' },
      { word: 'coral', meaning: '珊瑚', phonetic: '/ˈkɔːrəl/' },
      // Module 3 Forests and land
      { word: 'forest', meaning: '森林', phonetic: '/ˈfɔːrɪst/' },
      { word: 'land', meaning: '陆地', phonetic: '/lænd/' },
      { word: 'earth', meaning: '地球', phonetic: '/ɜːrθ/' },
      { word: 'environment', meaning: '环境', phonetic: '/ɪnˈvaɪrənmənt/' },
      { word: 'protect', meaning: '保护', phonetic: '/prəˈtekt/' },
      { word: 'destroy', meaning: '破坏', phonetic: '/dɪˈstrɔɪ/' },
      { word: 'animal', meaning: '动物', phonetic: '/ˈænɪml/' },
      { word: 'plant', meaning: '植物', phonetic: '/plænt/' },
      { word: 'wild', meaning: '野生的', phonetic: '/waɪld/' },
      { word: 'endangered', meaning: '濒危的', phonetic: '/ɪnˈdeɪndʒərd/' },
      { word: 'disappear', meaning: '消失', phonetic: '/ˌdɪsəˈpɪr/' },
      // Module 4 Controlling fire
      { word: 'fire', meaning: '火', phonetic: '/faɪər/' },
      { word: 'firefighter', meaning: '消防员', phonetic: '/ˈfaɪərfaɪtər/' },
      { word: 'fire engine', meaning: '消防车', phonetic: '/faɪər ˈendʒɪn/' },
      { word: 'alarm', meaning: '警报', phonetic: '/əˈlɑːrm/' },
      { word: 'escape', meaning: '逃生', phonetic: '/ɪˈskeɪp/' },
      { word: 'extinguisher', meaning: '灭火器', phonetic: '/ɪkˈstɪŋɡwɪʃər/' },
      { word: 'safety', meaning: '安全', phonetic: '/ˈseɪfti/' },
      { word: 'dangerous', meaning: '危险的', phonetic: '/ˈdeɪndʒərəs/' },
      { word: 'prevent', meaning: '预防', phonetic: '/prɪˈvent/' },
      { word: 'cause', meaning: '引起', phonetic: '/kɔːz/' },
      { word: 'match', meaning: '火柴', phonetic: '/mætʃ/' },
      { word: 'smoke', meaning: '烟', phonetic: '/smoʊk/' },
      { word: 'burn', meaning: '燃烧', phonetic: '/bɜːrn/' },
    ],
  },
}

/**
 * 获取所有预设词库名称列表
 */
export function getPresetNames(): string[] {
  return Object.keys(shenzhenPrimaryVocab)
}

/**
 * 获取指定预设词库
 */
export function getPresetVocab(name: string): PresetVocab | undefined {
  return shenzhenPrimaryVocab[name]
}

/**
 * 获取预设词库单词数量
 */
export function getPresetCount(name: string): number {
  return shenzhenPrimaryVocab[name]?.words.length || 0
}
